import type { OnboardingStep } from "./onboardingTypes";

export const DEVICE_ANALYSIS_ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: "welcome",
    page: "data",
    placement: "center",
    backdropMode: "full",
    backdropOpacity: 0.68,
    titleKey: "da_onboarding_welcome_title",
    bodyKey: "da_onboarding_welcome_body",
  },
  {
    id: "import",
    page: "data",
    placement: "right",
    ringTargetIds: ["device-analysis-import-csv-btn"],
    ringPadding: 6,
    spotlightTargetIds: ["device-analysis-import-card"],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_import_title",
    bodyKey: "da_onboarding_import_body",
  },
  {
    id: "template",
    page: "data",
    placement: "left",
    ringTargetIds: ["device-analysis-template-input-field"],
    ringPadding: 4,
    spotlightTargetIds: ["device-analysis-template-manager"],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_template_title",
    bodyKey: "da_onboarding_template_body",
  },
  {
    id: "template-config",
    page: "data",
    placement: "left",
    ringTargetIds: ["device-analysis-template-mode-tab-save"],
    spotlightTargetIds: ["device-analysis-template-manager"],
    spotlightPadding: 4,
    titleKey: "da_onboarding_template_config_title",
    bodyKey: "da_onboarding_template_config_body",
  },
  {
    id: "template-select-columns",
    page: "data",
    placement: "left",
    spotlightTargetIds: [
      "device-analysis-preview-canvas-grid",
      "device-analysis-template-selected-columns",
    ],
    titleKey: "da_onboarding_template_select_columns_title",
    bodyKey: "da_onboarding_template_select_columns_body",
  },
  {
    id: "template-save",
    page: "data",
    placement: "left",
    ringTargetIds: ["device-analysis-template-save-btn"],
    spotlightTargetIds: ["device-analysis-template-mode-panel-save"],
    titleKey: "da_onboarding_template_save_title",
    bodyKey: "da_onboarding_template_save_body",
  },
  {
    id: "apply",
    page: "data",
    placement: "bottom",
    ringTargetIds: ["device-analysis-template-apply-to-all"],
    spotlightTargetIds: ["device-analysis-template-manager"],
    spotlightPadding: 4,
    titleKey: "da_onboarding_apply_title",
    bodyKey: "da_onboarding_apply_body",
  },
  {
    id: "analysis",
    page: "analysis",
    placement: "right",
    spotlightTargetIds: [
      "device-analysis-tabpanel-analysis",
    ],
    titleKey: "da_onboarding_analysis_title",
    bodyKey: "da_onboarding_analysis_body",
  },
  {
    id: "origin-export",
    page: "analysis",
    placement: "bottom",
    ringTargetIds: ["device-analysis-window-origin-btn"],
    spotlightTargetIds: ["device-analysis-tabpanel-analysis"],
    titleKey: "da_onboarding_origin_export_title",
    bodyKey: "da_onboarding_origin_export_body",
  },
  {
    id: "origin-settings",
    page: "settings",
    placement: "bottom",
    ringTargetIds: ["device-analysis-settings-origin-path-choose-btn"],
    spotlightTargetIds: ["device-analysis-settings-origin-path-card"],
    titleKey: "da_onboarding_origin_title",
    bodyKey: "da_onboarding_origin_body",
  },
  {
    id: "finish",
    page: "settings",
    placement: "center",
    titleKey: "da_onboarding_finish_title",
    bodyKey: "da_onboarding_finish_body",
  },
];
