import type { OnboardingStep } from "./onboardingTypes";

const TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS = [
  "device-analysis-template-manager",
  "device-analysis-preview-canvas-grid",
];

export const DEVICE_ANALYSIS_ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: "welcome",
    page: "data",
    placement: "center",
    backdropMode: "full",
    backdropOpacity: 0.68,
    titleKey: "da_onboarding_welcome_title",
    bodyKey: "da_onboarding_welcome_body",
  },
  {
    id: "import",
    page: "data",
    placement: "right",
    ringTargetIds: ["device-analysis-import-csv-btn"],
    ringPadding: 6,
    spotlightTargetIds: ["device-analysis-import-card"],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_import_title",
    bodyKey: "da_onboarding_import_body",
  },
  {
    id: "template",
    page: "data",
    placement: "left",
    ringTargetIds: ["device-analysis-template-input-field"],
    ringPadding: 4,
    spotlightTargetIds: ["device-analysis-template-manager"],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_template_title",
    bodyKey: "da_onboarding_template_body",
  },
  {
    id: "template-config",
    page: "data",
    placement: "left",
    progressGroupId: "template-config",
    ringTargetIds: ["device-analysis-template-mode-tab-save"],
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_template_config_title",
    bodyKey: "da_onboarding_template_config_body",
  },
  {
    id: "template-name",
    page: "data",
    placement: "left",
    progressGroupId: "template-config",
    ringTargetIds: ["device-analysis-template-name-row"],
    ringPadding: 4,
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    focusTargetId: "device-analysis-template-name",
    titleKey: "da_onboarding_template_name_title",
    bodyKey: "da_onboarding_template_name_body",
  },
  {
    id: "template-x-start",
    page: "data",
    placement: "left",
    progressGroupId: "template-config",
    ringTargetIds: ["device-analysis-template-x-data-start"],
    ringActivationTargetIds: ["device-analysis-template-x-data-start"],
    activatedRingVirtualTargets: [
      {
        kind: "preview-cell",
        anchorId: "device-analysis-preview-canvas-grid",
        rowIndex: 5,
        colIndex: 0,
      },
    ],
    ringPadding: 4,
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    focusTargetId: "device-analysis-template-x-data-start",
    titleKey: "da_onboarding_template_x_start_title",
    bodyKey: "da_onboarding_template_x_start_body",
  },
  {
    id: "template-x-end",
    page: "data",
    placement: "left",
    progressGroupId: "template-config",
    ringTargetIds: ["device-analysis-template-x-data-end"],
    ringPadding: 4,
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    focusTargetId: "device-analysis-template-x-data-end",
    titleKey: "da_onboarding_template_x_end_title",
    bodyKey: "da_onboarding_template_x_end_body",
  },
  {
    id: "template-x-points",
    page: "data",
    placement: "left",
    progressGroupId: "template-config",
    ringTargetIds: ["device-analysis-template-x-points"],
    ringPadding: 4,
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    focusTargetId: "device-analysis-template-x-points",
    titleKey: "da_onboarding_template_x_points_title",
    bodyKey: "da_onboarding_template_x_points_body",
  },
  {
    id: "template-select-columns",
    page: "data",
    placement: "left",
    progressGroupId: "template-config",
    ringTargetIds: ["device-analysis-preview-column-selector-row"],
    ringPadding: 4,
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_template_select_columns_title",
    bodyKey: "da_onboarding_template_select_columns_body",
  },
  {
    id: "template-save",
    page: "data",
    placement: "left",
    ringTargetIds: ["device-analysis-template-save-btn"],
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_template_save_title",
    bodyKey: "da_onboarding_template_save_body",
  },
  {
    id: "apply",
    page: "data",
    placement: "left",
    ringTargetIds: ["device-analysis-template-apply-to-all"],
    spotlightTargetIds: ["device-analysis-template-manager"],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_apply_title",
    bodyKey: "da_onboarding_apply_body",
  },
  {
    id: "analysis",
    page: "analysis",
    placement: "right",
    spotlightTargetIds: [
      "device-analysis-tabpanel-analysis",
    ],
    titleKey: "da_onboarding_analysis_title",
    bodyKey: "da_onboarding_analysis_body",
  },
  {
    id: "origin-export",
    page: "analysis",
    placement: "bottom",
    ringTargetIds: ["device-analysis-window-origin-btn"],
    spotlightTargetIds: ["device-analysis-tabpanel-analysis"],
    titleKey: "da_onboarding_origin_export_title",
    bodyKey: "da_onboarding_origin_export_body",
  },
  {
    id: "origin-settings",
    page: "settings",
    placement: "bottom",
    ringTargetIds: ["device-analysis-settings-origin-path-choose-btn"],
    spotlightTargetIds: ["device-analysis-settings-origin-path-card"],
    titleKey: "da_onboarding_origin_title",
    bodyKey: "da_onboarding_origin_body",
  },
  {
    id: "finish",
    page: "settings",
    placement: "center",
    titleKey: "da_onboarding_finish_title",
    bodyKey: "da_onboarding_finish_body",
  },
];
