import type { OnboardingStep } from "./onboardingTypes";

const TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS = [
  "device-analysis-template-manager",
  "device-analysis-preview-canvas-grid",
];

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    id: "welcome",
    page: "data",
    placement: "center",
    backdropMode: "full",
    backdropOpacity: 0.68,
    titleKey: "da_onboarding_welcome_title",
    bodyKey: "da_onboarding_welcome_body",
  },
  {
    id: "import",
    page: "data",
    placement: "right",
    ringTargetIds: ["device-analysis-import-csv-btn"],
    ringPadding: 6,
    spotlightTargetIds: ["device-analysis-import-card"],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_import_title",
    bodyKey: "da_onboarding_import_body",
  },
  {
    id: "template",
    page: "data",
    placement: "left",
    ringTargetIds: ["device-analysis-template-dropdown-menu"],
    ringPadding: 4,
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_template_title",
    bodyKey: "da_onboarding_template_body",
  },
  {
    id: "template-custom",
    page: "data",
    placement: "left",
    ringTargetIds: ["device-analysis-template-mode-tab-save"],
    ringPadding: 4,
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    titleKey: "da_onboarding_apply_title",
    bodyKey: "da_onboarding_apply_body",
  },
  {
    id: "apply",
    page: "data",
    placement: "left",
    ringTargetIds: ["device-analysis-template-output-rule-apply-to-all"],
    spotlightTargetIds: [...TEMPLATE_CONFIG_SPOTLIGHT_TARGET_IDS],
    spotlightPadding: 4,
    cardTargetIds: ["device-analysis-template-config-panel-content"],
    cardAnchor: "center",
    cardOffsetY: 100,
    titleKey: "da_onboarding_apply_run_title",
    bodyKey: "da_onboarding_apply_run_body",
  },
  {
    id: "analysis-chart",
    page: "analysis",
    placement: "right",
    progressGroupId: "analysis",
    spotlightVirtualTargets: [{ kind: "analysis-chart-section" }],
    spotlightPadding: 4,
    titleKey: "da_onboarding_analysis_chart_title",
    bodyKey: "da_onboarding_analysis_chart_body",
  },
  {
    id: "analysis-overview",
    page: "analysis",
    placement: "right",
    progressGroupId: "analysis",
    spotlightTargetIds: ["device-analysis-overview-sidebar"],
    spotlightPadding: 4,
    titleKey: "da_onboarding_analysis_overview_title",
    bodyKey: "da_onboarding_analysis_overview_body",
  },
  {
    id: "analysis-calculated",
    page: "analysis",
    placement: "top",
    progressGroupId: "analysis",
    spotlightVirtualTargets: [{ kind: "analysis-calculated-section" }],
    spotlightPadding: 4,
    titleKey: "da_onboarding_analysis_calculated_title",
    bodyKey: "da_onboarding_analysis_calculated_body",
  },
  {
    id: "origin-export",
    page: "analysis",
    placement: "left",
    spotlightTargetIds: ["device-analysis-window-origin-btn"],
    spotlightPadding: 2,
    cardOffsetY: 28,
    titleKey: "da_onboarding_origin_export_title",
    bodyKey: "da_onboarding_origin_export_body",
  },
  {
    id: "origin-settings",
    page: "settings",
    placement: "bottom",
    ringTargetIds: ["device-analysis-settings-origin-health-check-btn"],
    spotlightTargetIds: ["device-analysis-settings-origin-path-card"],
    spotlightPadding: 0,
    cardTargetIds: ["device-analysis-settings-origin-path-card"],
    cardAnchor: "top-center",
    cardOffsetY: -248,
    focusTargetId: "device-analysis-settings-origin-path-card",
    titleKey: "da_onboarding_origin_title",
    bodyKey: "da_onboarding_origin_body",
  },
  {
    id: "finish",
    page: "settings",
    placement: "center",
    titleKey: "da_onboarding_finish_title",
    bodyKey: "da_onboarding_finish_body",
  },
];
