import test from "node:test";
import assert from "node:assert/strict";
import {
  DEFAULT_SIDEBAR_WIDTH_PX,
  DEVICE_ANALYSIS_TEMPLATE_MODE_ICON_ONLY_THRESHOLD_PX,
  MAX_DEVICE_ANALYSIS_SIDEBAR_WIDTH_PX,
  MIN_DEVICE_ANALYSIS_SIDEBAR_WIDTH_PX,
} from "./layout.ts";

test("sidebar width constants remain in a valid order", () => {
  assert.ok(MIN_DEVICE_ANALYSIS_SIDEBAR_WIDTH_PX < DEFAULT_SIDEBAR_WIDTH_PX);
  assert.ok(DEFAULT_SIDEBAR_WIDTH_PX < MAX_DEVICE_ANALYSIS_SIDEBAR_WIDTH_PX);
  assert.ok(
    MIN_DEVICE_ANALYSIS_SIDEBAR_WIDTH_PX <
      DEVICE_ANALYSIS_TEMPLATE_MODE_ICON_ONLY_THRESHOLD_PX,
  );
  assert.ok(
    DEVICE_ANALYSIS_TEMPLATE_MODE_ICON_ONLY_THRESHOLD_PX <
      DEFAULT_SIDEBAR_WIDTH_PX,
  );
});
