export const DEFAULT_SIDEBAR_WIDTH_PX = 280;
export const MIN_DEVICE_ANALYSIS_SIDEBAR_WIDTH_PX = 200;
export const MAX_DEVICE_ANALYSIS_SIDEBAR_WIDTH_PX = 600;
export const DEVICE_ANALYSIS_TEMPLATE_MODE_ICON_ONLY_THRESHOLD_PX = 250;
