export const TABLE_UI_CHUNK_SIZE_ROWS = 50;
export const TABLE_MAX_CACHED_UI_ROWS_PER_FILE = 5000;
export const TABLE_MAX_CACHED_FILES = 20;

export const DA_PREVIEW_UI_CHUNK_SIZE_ROWS = TABLE_UI_CHUNK_SIZE_ROWS;
export const DA_PREVIEW_MAX_CACHED_UI_ROWS_PER_FILE = TABLE_MAX_CACHED_UI_ROWS_PER_FILE;
export const DA_PREVIEW_MAX_CACHED_FILES = TABLE_MAX_CACHED_FILES;
