export const workbenchIpcChannels = {
  desktopAutoUpdateStatusGet: "desktop:auto-update-status:get",
  desktopAutoUpdateStatusChanged: "desktop:auto-update-status:changed",
  desktopAutoUpdateCheck: "desktop:auto-update:check",
  desktopAutoUpdateCheckAndInstall: "desktop:auto-update:check-and-install",
  desktopAutoUpdateInstallDownloaded: "desktop:auto-update:install-downloaded",
  desktopAppearanceSet: "conductor:desktop:appearance:set",
  templatesGet: "store:templates:get",
  templatesCreate: "store:templates:create",
  templatesDelete: "store:templates:delete",
  settingsGet: "store:settings:get",
  settingsPatch: "store:settings:patch",
  persistencePathGet: "store:persistence-path:get",
  persistencePathSet: "store:persistence-path:set",
  persistencePathChoose: "store:persistence-path:choose",
  originExeGet: "origin:exe:get",
  originExeSet: "origin:exe:set",
  originExePick: "origin:exe:pick",
  originHealthCheck: "origin:health-check",
  originRunCsv: "origin:run-csv",
  originRuntimeCleanupRun: "origin:runtime-cleanup:run",
  importPrepareRust: "import:prepare-rust",
  excelConvertRust: "excel:convert-rust",
  excelReadConvertedCsv: "excel:read-converted-csv",
  analysisDemoFilesGet: "demo:files:get",
  analysisRustEngineOpen: "rust:open",
  analysisRustEnginePreviewMeta: "rust:preview-meta",
  analysisRustEnginePreviewRows: "rust:preview-rows",
  analysisRustEngineReadCell: "rust:read-cell",
  analysisRustEngineReadCells: "rust:read-cells",
  analysisRustEngineInferAutoExtraction: "rust:infer-auto-extraction",
  analysisRustEngineProcessFile: "rust:process-file",
  analysisRustEngineAnalyzeRc: "rust:analyze-rc",
  analysisRustEngineExportOriginCsv: "rust:export-origin-csv",
  analysisOriginZipSave: "origin:zip:save",
  analysisRustEngineDispose: "rust:dispose",
} as const;

export type WorkbenchIpcChannel = (typeof workbenchIpcChannels)[keyof typeof workbenchIpcChannels];
