export const workbenchIpcChannels = {
  desktopAutoUpdateStatusGet: "conductor:desktop:auto-update-status:get",
  desktopAutoUpdateStatusChanged: "conductor:desktop:auto-update-status:changed",
  desktopAutoUpdateCheck: "conductor:desktop:auto-update:check",
  desktopAutoUpdateCheckAndInstall: "conductor:desktop:auto-update:check-and-install",
  desktopAutoUpdateInstallDownloaded: "conductor:desktop:auto-update:install-downloaded",
  desktopOpaqueSurfaceChanged: "conductor:desktop:opaque-surface:changed",
  desktopAppearanceSet: "conductor:desktop:appearance:set",
  originExeGet: "conductor:origin:exe:get",
  originExeSet: "conductor:origin:exe:set",
  originExePick: "conductor:origin:exe:pick",
  originHealthCheck: "conductor:origin:health-check",
  originRunCsv: "conductor:origin:run-csv",
  originRuntimeCleanupRun: "conductor:origin:runtime-cleanup:run",
  fileConversionPrepare: "conductor:files:conversion:prepare",
  excelConvertRust: "conductor:excel:convert-rust",
  excelReadConvertedCsv: "conductor:excel:read-converted-csv",
  demoFilesGet: "conductor:demo:files:get",
  rustHostOpen: "conductor:rust:open",
  rustHostPreviewMeta: "conductor:rust:preview-meta",
  rustHostPreviewRows: "conductor:rust:preview-rows",
  rustHostReadCell: "conductor:rust:read-cell",
  rustHostReadCells: "conductor:rust:read-cells",
  rustHostProcessFile: "conductor:rust:process-file",
  rustHostCalculateRc: "conductor:rust:calculate-rc",
  rustHostExportOriginCsv: "conductor:rust:export-origin-csv",
  originZipSave: "conductor:origin:zip:save",
  rustHostDispose: "conductor:rust:dispose",
} as const;

export type WorkbenchIpcChannel = (typeof workbenchIpcChannels)[keyof typeof workbenchIpcChannels];
