import { useState } from 'react';
import { LanguageContext } from './language-context';

const translations = {
  en: {
    common_clear: 'Clear',
    da_analysis_visualization: 'Analysis & Visualization',
    da_apply_to_all_files: 'Apply to All',
    da_apply_to_new_files: 'Apply to New',
    da_apply_to_new_files_busy: 'Extraction is already running.',
    da_apply_to_new_files_no_new: 'No new files to extract.',
    da_apply_to_new_files_requires_full_apply: 'Apply to All first.',
    da_apply_to_new_files_requires_same_config: 'Template changed. Please Apply to All again.',
    da_csv_empty_browse: 'browse',
    da_csv_empty_subtitle_prefix: 'Drag files here or',
    da_curveTaggingFileNameBothRequired: 'When using file-name tagging, please provide keywords for both Vg and Vd.',
    da_curveTaggingModeExclusive: 'Curve tagging must use either Var1/Var2 or file-name keywords, not both.',
    da_data_extraction_template: 'Data Extraction Template',
    da_delete_template: 'Delete template',
    da_extractImportCsvFirst: 'Please import at least one CSV file first.',
    da_extractInvalidConfig: 'Invalid configuration.',
    da_extractInvalidXRange: 'Invalid X row range.',
    da_extractPointsCellPositiveInt: 'Points cell {cell} must contain a positive integer.',
    da_extractPointsCellTooLarge: 'Points from {cell} ({points}) cannot be larger than the X range length ({total}).',
    da_extractPreviewLoading: 'Preview is still loading. Please wait a moment and try again.',
    da_extractSelectYColumn: 'Please select at least one Y column (click column headers in the preview).',
    da_extractSetXEndOrUseEnd: 'Please set X Data end cell (e.g. A1408) or use \'End\' to read until the last preview row.',
    da_extractSetXStart: 'Please set X Data start cell (e.g. A2).',
    da_extractXNotDivisibleByPoints: 'X range has {total} points, which is not divisible by points={points}.',
    da_extractXNotDivisibleByPointsFromCell: 'X range has {total} points, which is not divisible by points={points} (from {cell}).',
    da_extractXPointsPositiveIntOrCell: 'X Points must be a positive integer (or a cell like B2).',
    da_extractXPointsTooLarge: 'X Points ({points}) cannot be larger than the X range length ({total}).',
    da_extractXSameColumn: 'X Data start/end must be in the same column.',
    da_extractYCannotIncludeX: 'Y columns cannot include the X column.',
    da_extractYCountCellPositiveInt: 'Y Data Count cell {cell} must contain a positive integer.',
    da_extractYCountPositiveIntOrCell: 'Y Data Count must be a positive integer (or a cell like B2).',
    da_extractYStartEndValidCells: 'Y Data start/end must be valid cells (e.g. B2 and D2).',
    da_extractYStepCellPositiveNumber: 'Y Data Step cell {cell} must contain a positive number.',
    da_extractYStepPositiveNumberOrCell: 'Y Data Step must be a positive number (or a cell like B2).',
    da_extract_groups_suffix: ', {groups} group(s)',
    da_extract_points_fixed: 'points={points}',
    da_extract_points_from_cell: 'points from {cell}',
    da_extract_started: 'Started extracting {count} file(s) ({detail}{groups}). Charts will appear progressively.{warnings}',
    da_extract_started_incremental: 'Started extracting {count} new file(s) ({detail}{groups}). Charts will appear progressively.{warnings}',
    da_extract_warnings_block: '\n\nWarnings:\n- {warnings}',
    da_extraction_errors: 'Extraction errors',
    da_general_template: 'General Template',
    da_import: 'Data Import',
    da_import_csv: 'Import CSV',
    da_import_section: 'Import CSV files',
    da_menu_app: 'Device Analysis Studio',
    da_menu_export_origin_zip: 'Export Origin ZIP',
    da_menu_export_zip: 'Export Analysis ZIP',
    da_menu_file: 'File',
    da_menu_help: 'Help',
    da_menu_import_csv: 'Import CSV',
    da_menu_language_en: 'Language: English',
    da_menu_language_zh: 'Language: Chinese',
    da_menu_page_analysis: 'Go to Analysis Page',
    da_menu_page_data: 'Go to Data Page',
    da_menu_reload_window: 'Reload Window',
    da_menu_reset_session: 'Reset Session',
    da_menu_shortcut_ctrl_o: 'Ctrl+O',
    da_menu_shortcut_ctrl_shift_e: 'Ctrl+Shift+E',
    da_menu_shortcut_f12: 'F12',
    da_menu_shortcut_f5: 'F5',
    da_menu_theme_dark: 'Theme: Dark',
    da_menu_theme_light: 'Theme: Light',
    da_menu_theme_system: 'Theme: System',
    da_menu_toggle_devtools: 'Toggle DevTools',
    da_menu_view: 'View',
    da_menu_window_close: 'Close Window',
    da_menu_window_maximize: 'Maximize / Restore',
    da_menu_window_minimize: 'Minimize Window',
    da_invalidVarPair: 'Invalid Var1/Var2 configuration',
    da_loadTemplatesFailed: 'Failed to load templates: {error}',
    da_loaded_csv_files: 'Loaded {count} CSV files',
    da_match_by_file_name: 'Match by file name',
    da_new_template: 'New template',
    da_no_processed_data: 'No Processed Data',
    da_no_processed_data_hint: 'Apply a template above to generate results.',
    da_no_saved_templates: 'No saved templates',
    da_preview_error: 'Preview failed to load',
    da_preview_error_hint: 'Please try selecting the file again.',
    da_preview_filename_label: 'Filename',
    da_preview_loading: 'Loading preview...',
    da_preview_loading_hint: 'Parsing CSV preview, please wait.',
    da_preview_select_file_hint: 'Select a file to preview',
    da_reset_session: 'Reset session',
    da_save_template: 'Save template',
    da_stop_on_first_invalid_file: 'Stop on first invalid file',
    da_tab_analysis: 'Analysis & Visualization',
    da_tab_data: 'Import & Extraction',
    da_tab_switcher_label: 'Device analysis page switcher',
    da_template_discard_changes_desc: 'You have unsaved edits in the Save panel. Discard them and return to Select?',
    da_template_discard_changes_discard: 'Discard changes',
    da_template_discard_changes_keep_editing: 'Keep editing',
    da_template_discard_changes_title: 'Discard changes?',
    da_template_mode: 'Template mode',
    da_template_mode_save: 'Save',
    da_template_mode_select: 'Select',
    da_template_name: 'Template name',
    da_template_saved: 'Template saved',
    da_varPairBothOrNeither: 'Var1 and Var2 must both be empty or both filled.',
    da_varPairCellOrText: 'Var1 and Var2 must both be cell refs (e.g. A1) or both be text (e.g. Vg). Do not mix.',
    da_yColumnsRequired: 'Please select Y data from the preview header columns.',
    unknownError: 'Unknown error',
  },
  zh: {
    common_clear: '清除',
    da_analysis_visualization: '分析与可视化',
    da_apply_to_all_files: '应用到所有',
    da_apply_to_new_files: '仅新增文件',
    da_apply_to_new_files_busy: '正在提取中，请稍后。',
    da_apply_to_new_files_no_new: '没有需要新增提取的文件。',
    da_apply_to_new_files_requires_full_apply: '请先点击“应用到所有”。',
    da_apply_to_new_files_requires_same_config: '模板配置已变更，请重新“应用到所有”。',
    da_csv_empty_browse: '浏览',
    da_csv_empty_subtitle_prefix: '拖拽文件到这里或',
    da_curveTaggingFileNameBothRequired: '使用文件名标注时，请同时填写 Vg 和 Vd 的关键词。',
    da_curveTaggingModeExclusive: '曲线标注方式只能二选一：使用 Var1/Var2 或使用文件名关键词，不能同时使用。',
    da_data_extraction_template: '数据提取',
    da_delete_template: '删除模板',
    da_extractImportCsvFirst: '请先导入至少一个 CSV 文件。',
    da_extractInvalidConfig: '配置不合法。',
    da_extractInvalidXRange: 'X 行范围不合法。',
    da_extractPointsCellPositiveInt: 'Points 单元格 {cell} 必须为正整数。',
    da_extractPointsCellTooLarge: 'Points {cell} 的值（{points}）不能大于 X 范围长度（{total}）。',
    da_extractPreviewLoading: '预览仍在加载中，请稍等后重试。',
    da_extractSelectYColumn: '请至少选择一个 Y 列（点击预览表头列名）。',
    da_extractSetXEndOrUseEnd: '请设置 X 数据结束单元格（例如 A1408），或使用 \'End\' 读取到预览的最后一行。',
    da_extractSetXStart: '请设置 X 数据起始单元格（例如 A2）。',
    da_extractXNotDivisibleByPoints: 'X 范围共有 {total} 个点，无法被 points={points} 整除。',
    da_extractXNotDivisibleByPointsFromCell: 'X 范围共有 {total} 个点，无法被 points={points}（来自 {cell}）整除。',
    da_extractXPointsPositiveIntOrCell: 'X Points 必须为正整数（或单元格如 B2）。',
    da_extractXPointsTooLarge: 'X Points（{points}）不能大于 X 范围长度（{total}）。',
    da_extractXSameColumn: 'X 数据起止必须在同一列。',
    da_extractYCannotIncludeX: 'Y 列不能包含 X 列。',
    da_extractYCountCellPositiveInt: 'Y Data Count 单元格 {cell} 必须为正整数。',
    da_extractYCountPositiveIntOrCell: 'Y Data Count 必须为正整数（或单元格如 B2）。',
    da_extractYStartEndValidCells: 'Y 数据起止必须为有效单元格（例如 B2 和 D2）。',
    da_extractYStepCellPositiveNumber: 'Y Data Step 单元格 {cell} 必须为正数。',
    da_extractYStepPositiveNumberOrCell: 'Y Data Step 必须为正数（或单元格如 B2）。',
    da_extract_groups_suffix: '，{groups} 组',
    da_extract_points_fixed: '点数={points}',
    da_extract_points_from_cell: '点数来自 {cell}',
    da_extract_started: '开始提取 {count} 个文件（{detail}{groups}）。图表将逐步显示。{warnings}',
    da_extract_started_incremental: '开始提取 {count} 个新增文件（{detail}{groups}）。图表将逐步显示。{warnings}',
    da_extract_warnings_block: '\n\n警告：\n- {warnings}',
    da_extraction_errors: '提取错误',
    da_general_template: '通用模板',
    da_import: '数据导入',
    da_import_csv: '导入 CSV',
    da_import_section: '数据导入',
    da_menu_app: 'Device Analysis Studio',
    da_menu_export_origin_zip: '导出 Origin 压缩包',
    da_menu_export_zip: '导出分析压缩包',
    da_menu_file: '文件',
    da_menu_help: '帮助',
    da_menu_import_csv: '导入 CSV',
    da_menu_language_en: '语言：英文',
    da_menu_language_zh: '语言：中文',
    da_menu_page_analysis: '切换到分析页',
    da_menu_page_data: '切换到数据页',
    da_menu_reload_window: '重新加载窗口',
    da_menu_reset_session: '重置会话',
    da_menu_shortcut_ctrl_o: 'Ctrl+O',
    da_menu_shortcut_ctrl_shift_e: 'Ctrl+Shift+E',
    da_menu_shortcut_f12: 'F12',
    da_menu_shortcut_f5: 'F5',
    da_menu_theme_dark: '主题：深色',
    da_menu_theme_light: '主题：浅色',
    da_menu_theme_system: '主题：跟随系统',
    da_menu_toggle_devtools: '切换开发者工具',
    da_menu_view: '视图',
    da_menu_window_close: '关闭窗口',
    da_menu_window_maximize: '最大化 / 还原',
    da_menu_window_minimize: '最小化窗口',
    da_invalidVarPair: 'Var1/Var2 配置不合法',
    da_loadTemplatesFailed: '模板加载失败：{error}',
    da_loaded_csv_files: '已加载 {count} 个 CSV 文件',
    da_match_by_file_name: '按文件名匹配',
    da_new_template: '新建模板',
    da_no_processed_data: '暂无处理结果',
    da_no_processed_data_hint: '请先在上方应用模板以生成结果。',
    da_no_saved_templates: '暂无已保存模板',
    da_preview_error: '预览加载失败',
    da_preview_error_hint: '请尝试重新选择该文件',
    da_preview_filename_label: '文件名',
    da_preview_loading: '预览加载中...',
    da_preview_loading_hint: '正在解析 CSV 预览，请稍候。',
    da_preview_select_file_hint: '请选择文件以预览',
    da_reset_session: '重置会话',
    da_save_template: '保存模板',
    da_stop_on_first_invalid_file: '首个无效即停止',
    da_tab_analysis: '分析与可视化',
    da_tab_data: '导入与提取',
    da_tab_switcher_label: '设备分析页面切换',
    da_template_discard_changes_desc: '你在“保存”面板有未保存的修改。要放弃这些修改并返回“选择”吗？',
    da_template_discard_changes_discard: '放弃修改',
    da_template_discard_changes_keep_editing: '继续编辑',
    da_template_discard_changes_title: '放弃修改？',
    da_template_mode: '模板模式',
    da_template_mode_save: '保存',
    da_template_mode_select: '选择',
    da_template_name: '模板名称',
    da_template_saved: '模板已保存',
    da_varPairBothOrNeither: 'Var1 和 Var2 必须同时留空或同时填写。',
    da_varPairCellOrText: 'Var1 和 Var2 只能同时使用单元格（如 A1）或同时使用文本（如 Vg），不允许混用。',
    da_yColumnsRequired: '请从预览表头中选择 Y 数据列。',
    unknownError: '未知错误',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('zh');

  const t = (key, vars) => {
    const template = translations[language]?.[key] ?? translations.en?.[key] ?? key;
    if (!vars || typeof template !== 'string') return template;

    return Object.entries(vars).reduce((acc, [varKey, value]) => {
      return acc.replaceAll('{' + varKey + '}', String(value));
    }, template);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
