import { useState } from 'react';
import { LanguageContext } from './language-context';

const translations = {
  en: {
    typography_demo_title: 'Typography Demo',
    typography_demo_desc:
      'Preview the project type scale (families + sizes). Numbers are Tailwind defaults unless overridden.',
    journal_links: 'Journal links',
    literature_status_ready: 'Ready',
    literature_source_nature: 'Nature',
    literature_source_science: 'Science',
    literature_source_acs: 'ACS',
    literature_source_wiley: 'Wiley',
    literature_source_unsupported: 'Unsupported',
    literature_seed_url_placeholder: 'Article URL',
    literature_seed_title_placeholder: 'Title',
    literature_max_results_invalid: 'Max results must be a number.',
    settings: 'Settings',
    appearance: 'Appearance',
    language: 'Language',
    profile: 'Profile',
    security: 'Security',
    dataRetention: 'Data Retention',
    retentionHint: 'Logs are capped by count: when over the limit, the oldest entries are removed automatically.',
    logsMaxCount: 'Max logs kept',
    logsRetentionDays: 'Log retention (days)',
    requestsRetentionDays: 'Message retention (days)',
    lastCleanupAt: 'Last trim',
    nextCleanupAt: 'Next cleanup',
    runCleanupNow: 'Trim now',
    retentionLoadFailed: 'Failed to load retention settings',
    retentionCleanupFailed: 'Cleanup failed',
    passwordMismatch: 'Passwords do not match',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    changeAvatar: 'Change Avatar',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    saveChanges: 'Save',
    dashboard: 'Dashboard',
    overview: 'Reservation Overview',
    device_analysis: 'Device Analysis',
    device_analysis_subtitle: 'Import, extract, and visualize device data',
    da_import_section: 'Import CSV files',
    da_import: 'Data Import',
    da_import_csv: 'Import CSV',
    da_csv_empty_title: 'Upload CSV files',
    da_csv_empty_subtitle_prefix: 'Drag files here or',
    da_csv_empty_browse: 'browse',
    da_loaded_csv_files: 'Loaded {count} CSV files',
    da_reset_session: 'Reset session',
    da_extraction_errors: 'Extraction errors',
    da_data_extraction_template: 'Data Extraction Template',
    da_apply_to_all_files: 'Apply to All',
    da_apply_to_new_files: 'Apply to New',
    da_apply_to_new_files_busy: 'Extraction is already running.',
    da_apply_to_new_files_no_new: 'No new files to extract.',
    da_apply_to_new_files_requires_full_apply: 'Apply to All first.',
    da_apply_to_new_files_requires_same_config:
      'Template changed. Please Apply to All again.',
    da_stop_on_first_invalid_file: 'Stop on first invalid file',
    da_save_template: 'Save template',
    da_template_discard_changes_title: 'Discard changes?',
    da_template_discard_changes_desc:
      'You have unsaved edits in the Save panel. Discard them and return to Select?',
    da_template_discard_changes_keep_editing: 'Keep editing',
    da_template_discard_changes_discard: 'Discard changes',
    da_new_template: 'New template',
    da_delete_template: 'Delete template',
    da_no_saved_templates: 'No saved templates',
    da_template_name: 'Template name',
    da_general_template: 'General Template',
    da_template_mode: 'Template mode',
    da_template_mode_select: 'Select',
    da_template_mode_save: 'Save',
    da_match_by_file_name: 'Match by file name',
    da_analysis_visualization: 'Analysis & Visualization',
    da_view_table: 'Data Table',
    da_view_charts: 'Charts',
    da_no_processed_data: 'No Processed Data',
    da_no_processed_data_hint: 'Apply a template above to generate results.',
    da_no_data_extracted: 'No data extracted yet.',
    da_no_data_extracted_hint: 'Import CSVs and apply a template to see results.',
    da_no_file_selected: 'No file selected',
    da_preview_loading: 'Loading preview...',
    da_preview_loading_hint: 'Parsing CSV preview, please wait.',
    da_preview_error: 'Preview failed to load',
    da_preview_error_hint: 'Please try selecting the file again.',
    da_preview_select_file_hint: 'Select a file to preview',
    da_preview_filename_label: 'Filename',
    da_extract_started:
      'Started extracting {count} file(s) ({detail}{groups}). Charts will appear progressively.{warnings}',
    da_extract_started_incremental:
      'Started extracting {count} new file(s) ({detail}{groups}). Charts will appear progressively.{warnings}',
    da_extract_points_from_cell: 'points from {cell}',
    da_extract_points_fixed: 'points={points}',
    da_extract_groups_suffix: ', {groups} group(s)',
    da_extract_warnings_block: '\n\nWarnings:\n- {warnings}',
    da_select_series: 'Select series',
    common_clear: 'Clear',
    common_close: 'Close',
    bg_scale_compare_title: 'Background scale swatches',
    bg_scale_compare_desc: 'Preview Tailwind tokens and the proposed warm scale.',
    bg_scale_compare_current: 'Current (Tailwind tokens)',
    bg_scale_compare_proposed_warm: 'Proposed (warm, 0–500)',
    card_demo_title: 'Card Demo',
    card_demo_desc:
      'Inspect the Card root element in DevTools: `data-cta*` / `id` / `aria-label`.',
    card_demo_marker: 'Marker text (child content)',
    card_demo_default: 'Default',
    card_demo_panel: 'Panel',
    card_demo_flat: 'Flat',
    card_demo_glass: 'Glass',
    card_demo_default_aria: 'Card demo: default',
    card_demo_panel_aria: 'Card demo: panel',
    card_demo_flat_aria: 'Card demo: flat',
    card_demo_glass_aria: 'Card demo: glass',
    devices: 'Devices',
    booking: 'Booking',
    messages: 'Messages',
    literature_research: 'Literature Research',
    literature_research_title: 'Literature Research',
    literature_research_subtitle: 'Enter section URLs, filter by date, and extract abstracts.',
    literature_filters: 'Fetch Settings',
    literature_filters_hint: 'Supports Nature / Science (Science uses RSS + Crossref for abstracts).',
    literature_fetching: 'Fetching...',
    literature_fetch: 'Fetch',
    literature_seed_urls: 'Seed URLs',
    literature_add_url: 'Add URL',
    literature_remove_url: 'Remove',
    literature_seed_urls_hint: 'Tip: For Science pages (e.g. /journal/sciadv), we map them to RSS feeds automatically.',
    literature_seed_urls_hint_nature: 'Tip: Supports Research Articles page URLs for Nature and its various journals.',
    literature_seed_urls_hint_science: 'Tip: For Science, we use RSS + Crossref for abstracts. You can paste the section URL directly.',
    literature_start_date: 'Start date',
    literature_end_date: 'End date',
    literature_max_results: 'Max',
    literature_max_results_hint: 'Recommended ≤ 100',
    literature_results: 'Results',
    literature_results_title: 'Search Results',
    literature_keyword_matching: 'Keyword Matching',
    literature_results_count: 'items',
    literature_no_results: 'No matching articles',
    literature_no_results_hint: 'Try adjusting the date range or seed URLs.',
    literature_download: 'Download',
    literature_download_unavailable: 'No downloadable file',
    literature_no_abstract: '(No abstract available)',
    literature_translate: 'Translate abstract to Chinese',
    literature_show_translation: 'Show Chinese translation',
    literature_show_original: 'Show original abstract',
    literature_translate_wait: 'Another translation is in progress. Please wait.',
    literature_translation_label: 'Translation',
    literature_translation_label_en: 'English translation',
    literature_translation_label_zh: 'Chinese translation',
    literature_translate_failed: 'Translation failed.',
    literature_translation_failed_fallback: '(Translation failed; original abstract follows.)',
    literature_export_docx: 'Export DOCX',
    literature_export_docx_translating: 'Translating',
    literature_export_docx_building: 'Building DOCX...',
    literature_export_docx_success: 'DOCX exported.',
    literature_export_docx_failed: 'DOCX export failed.',
    literature_export_json: 'Export JSON',
    literature_export_json_success: 'JSON exported.',
    literature_export_json_missing_doi: 'JSON export blocked: some selected items are missing DOI.',
    literature_select_all_filtered: 'Select all',
    literature_deselect_all_filtered: 'Deselect all',
    literature_selected_count: 'Select',
    literature_clear_selection: 'Clear selection',
    literature_select_item: 'Select item',
    literature_clear_session: 'Clear page session',
    literature_session_cleared: 'Page session cleared.',
    literature_translate_test_title: 'Translation test',
    literature_translate_test_hint:
      'Translate a short text to confirm whether the personal key or the default key is being used.',
    literature_translate_test_placeholder: 'Paste a short English abstract here to test translation...',
    literature_translate_test_required: 'Please enter test text.',
    literature_translate_test_run: 'Test translate',
    literature_translate_test_running: 'Testing...',
    translation_service: 'Translation Service',
    literature_translate_test_used_key: 'Used key',
    literature_translate_test_key_user: 'personal',
    literature_translate_test_key_default: 'default',
    literature_translate_test_key_none: 'none',
    literature_translate_test_cached: 'cached',
    literature_translate_test_failed: 'Test failed',
    literature_translate_effective_key_source: 'Effective key source',
    literature_translate_test_bypass_cache: 'Force upstream (bypass cache)',
    literature_translate_test_force_default: 'Test with default key (global)',
    translation_provider: 'Translation provider',
    translation_provider_hint: 'Only one provider is active at a time.',
    default_provider: 'Default Provider (Global)',
    default_provider_hint: 'Used when you have not set a personal key/provider.',
    personal_provider: 'Personal Provider',
    personal_provider_hint:
      'Used with your personal key. Leave blank to use the default provider.',
    provider_current: 'Current provider',
    personal_provider_using_default: 'Using the default provider',
    personal_provider_requires_personal_key:
      'For security, personal provider is only used with a personal key.',
    translation_provider_required: 'Please enter your provider.',
    translation_provider_saved: 'Provider saved.',
    translation_provider_save_failed: 'Failed to save provider.',
    translation_provider_cleared: 'Provider cleared.',
    translation_provider_clear_failed: 'Failed to clear provider.',
    translation_provider_short: 'provider',
    translation_provider_switch_confirm:
      'Switching translation provider will clear the global default key/model/base URL. Continue?',
    translation_provider_updated: 'Translation provider updated.',
    translation_provider_update_failed: 'Failed to update provider.',
    translation_base_url_short: 'base URL',
    translation_model_short: 'model',
    personal_api_key: 'API Key',
    personal_api_key_hint:
      'Used for abstract translation. Stored for your user on the server; never shown in full once saved.',
    personal_api_key_placeholder: 'Paste your API key here...',
    personal_api_key_using_default:
      'Using the default key (admin). Set your own key to override.',
    personal_base_url: 'Base URL',
    personal_base_url_hint: 'Only used for OpenAI-compatible provider.',
    personal_base_url_placeholder: 'e.g. https://api.siliconflow.cn/v1',
    personal_base_url_saved: 'Base URL saved.',
    personal_base_url_save_failed: 'Failed to save base URL.',
    personal_base_url_cleared: 'Base URL cleared.',
    personal_base_url_clear_failed: 'Failed to clear base URL.',
    personal_base_url_using_default:
      'Using the default base URL (admin). Set your own base URL to override.',
    personal_base_url_requires_personal_key:
      'For security, personal base URL is only used with a personal key.',
    api_key_saved: 'Saved key',
    model_current: 'Current model',
    model_builtin: 'built-in',
    personal_model: 'Model',
    personal_model_hint:
      'Used with your personal key. Leave blank to use the default model.',
    personal_model_placeholder: 'e.g. glm-4.5-flash',
    personal_model_required: 'Please enter your model.',
    personal_model_saved: 'Model saved.',
    personal_model_save_failed: 'Failed to save model.',
    personal_model_cleared: 'Model cleared.',
    personal_model_clear_failed: 'Failed to clear model.',
    personal_model_using_default: 'Using the default model.',
    personal_model_requires_personal_key:
      'For security, personal model is only used with a personal key.',
    default_api_key: 'Default API Key (Global)',
    default_api_key_hint:
      'Used when a user has not set a personal key.',
    default_api_key_placeholder: 'Paste the default API key here...',
    default_model: 'Default Model (Global)',
    default_model_hint: 'Used with the global default key.',
    default_model_placeholder: 'e.g. glm-4.5-flash',
    default_base_url: 'Default Base URL (Global)',
    default_base_url_hint: 'Only used for OpenAI-compatible provider.',
    default_base_url_placeholder: 'e.g. https://api.siliconflow.cn/v1',
    default_base_url_required: 'Please enter the default base URL.',
    default_base_url_saved: 'Default base URL saved.',
    default_base_url_save_failed: 'Failed to save default base URL.',
    default_base_url_cleared: 'Default base URL cleared.',
    default_base_url_clear_failed: 'Failed to clear default base URL.',
    default_model_required: 'Please enter the default model.',
    default_model_saved: 'Default model saved.',
    default_model_save_failed: 'Failed to save default model.',
    default_model_cleared: 'Default model cleared.',
    default_model_clear_failed: 'Failed to clear default model.',
    default_api_key_required: 'Please enter the default API Key.',
    default_api_key_saved: 'Default API Key saved.',
    default_api_key_save_failed: 'Failed to save default API Key.',
    default_api_key_cleared: 'Default API Key cleared.',
    default_api_key_clear_failed: 'Failed to clear default API Key.',
    literature_save: 'Save',
    literature_clear: 'Clear',
    literature_saving: 'Saving...',
    personal_api_key_required: 'Please enter your API Key.',
    personal_api_key_saved: 'API Key saved.',
    personal_api_key_save_failed: 'Failed to save API Key.',
    personal_api_key_cleared: 'API Key cleared.',
    personal_api_key_clear_failed: 'Failed to clear API Key.',
    literature_use_examples: 'Use examples',
    literature_seed_urls_required:
      'Please select at least one seed URL (only nature.com / science.org / pubs.acs.org / *.onlinelibrary.wiley.com are supported).',
    literature_settings_loading: 'Loading settings...',
    literature_settings_saving: 'Saving settings...',
    literature_settings_saved: 'Settings saved',
    literature_settings_save_failed: 'Failed to save settings',
    literature_settings_save_failed_fetch_continues:
      "Couldn't sync settings. Fetch will continue with local inputs.",
    literature_keyword_filter: 'Keyword filter',
    literature_keyword_filter_hint: 'Filter after fetching; use the Unmatched view to check for omissions.',
    literature_match_any: 'Match any',
    literature_match_all: 'Match all',
    literature_clear_keywords: 'Clear keywords',
    literature_keywords_placeholder: 'Keyword matching: two-dimensional, wafer, AI, etc. (separate by spaces/newlines/commas)',
    literature_keywords_count: 'Keywords',
    literature_view_all: 'All',
    literature_view_matched: 'Matched',
    literature_view_unmatched: 'Unmatched',
    literature_sort: 'Sort',
    literature_sort_source: 'Fetch order',
    literature_sort_date: 'By date',
    literature_order_warning_rss_fallback:
      "Using RSS order because Wiley page HTML couldn't be fetched. Results may be out of order or incomplete.",
    literature_order_warning_rss_fallback_blocked:
      "Wiley blocked our HTML request (Cloudflare). Showing RSS order; results may be out of order or incomplete.",
    chinese: 'Chinese',
    english: 'English',
    inventory: 'Inventory Entry',
    request: 'Request',
    requestUser: 'Request User',
    note: 'Note',
    requestModification: 'Request Modification',
    contactAdmin: 'Please contact an administrator to modify this item.',
    inventory_new_item: 'New Inventory Item',
    inventory_modification: 'Inventory Modification',
    requested_by: 'Requested by {name}',
    student_id: 'Student ID',
    common_not_provided: 'Not provided',
    inventory_item_details: 'Item Details',
    inventory_changes: 'Changes',
    inventory_changes_breakdown: 'Changes Breakdown',
    inventory_field: 'Field',
    inventory_original: 'Original',
    inventory_new_value: 'New Value',
    quantity: 'Quantity',
    actions: 'Actions',
    addItem: 'Add Item',
    edit: 'Edit',
    cancel: 'Cancel',
    category: 'Category',
    itemName: 'Item Name',
    applicant: 'Applicant',
    inventoryList: 'Inventory List',
    date: 'Date',
    status: 'Status',
    reviewing: 'Reviewing',
    rejected: 'Rejected',
    approved: 'Approved',
    exampleItemName: 'e.g. iPhone 15',
    exampleCategory: 'e.g. Electronics',
    welcomeBack: 'Welcome back',
    upcomingReservations: 'Upcoming Reservations',
    reservedHours: 'Reserved Hours',
    hours: 'Hours',
    completed: 'Completed',
    recentActivity: 'Activity Notifications',
    recentMessages: 'Message Notifications',
    noActivity: 'No recent activity',
    noPendingRequests: 'No pending requests',
    confirmApproveAll: 'Confirm approve all?',
    approveAll: 'Approve',
    approveAllSuccess: 'Approved all.',
    approveAllFailed: 'Failed to approve all.',
    dashboard_tab_pending: 'Pending',
    dashboard_tab_reviewed: 'Reviewed',
    dashboard_no_reviewed_requests: 'No reviewed requests',
    dashboard_clear_reviewed: 'Clear reviewed',
    dashboard_confirm_clear_reviewed: 'Are you sure you want to clear reviewed records?',
    dashboard_clear_reviewed_success: 'Reviewed records cleared.',
    dashboard_clear_reviewed_failed: 'Failed to clear reviewed records.',
    systemUser: 'System',
    dashboard_activity_login_system: 'Logged in',
    dashboard_activity_create_reservation: 'Created reservation',
    dashboard_activity_cancel_reservation: 'Cancelled reservation',
    dashboard_activity_literature_research: 'Literature research',
    dashboard_activity_reservation_timeout: 'Reservation timed out',
    dashboard_activity_create_device: 'Created device',
    dashboard_activity_register_user: 'Registered user',
    dashboard_approve: 'Approve',
    dashboard_reject: 'Reject',
    dashboard_user_approved_success: 'User approved successfully',
    dashboard_request_approved_success: 'Request approved successfully',
    dashboard_failed_approve: 'Failed to approve',
    dashboard_processing: 'Processing...',
    dashboard_confirm_reject_user: 'Are you sure you want to reject this application?',
    dashboard_confirm_reject_request: 'Are you sure you want to reject this request?',
    dashboard_rejected_success: 'Rejected successfully',
    dashboard_failed_reject: 'Failed to reject',
    dashboard_confirm_revoke_request: 'Are you sure you want to revoke this request?',
    dashboard_revoke: 'Revoke',
    dashboard_request_revoked_success: 'Request revoked successfully',
    dashboard_failed_revoke_request: 'Failed to revoke request',
    dashboard_revoke_request: 'Revoke Request',
    dashboard_application_details: 'Application Details',
    dashboard_request_details: 'Message Details',
    dashboard_applied_for_account: 'Account application',
    dashboard_inventory_request: 'Inventory Request',
    dashboard_behavior: 'Behavior',
    dashboard_inventory_create: 'Inventory created',
    dashboard_inventory_update: 'Inventory updated',
    dashboard_user_col: 'User',
    createDevice: 'Create Device',
    createReservation: 'Create Reservation',
    registerUser: 'User Registered',
    logout: 'Logout',
    super_admin: 'Super Admin',
    admin: 'Admin',
    user: 'User',
    SUPER_ADMIN: 'Super Admin',
    ADMIN: 'Admin',
    USER: 'User',
    displayName: 'Display Name',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    password_placeholder: '********',
    limited_time: 'Limited Time',
    account_expiry: 'Account Expiry',
    account_status: 'Account Status',
    disabled: 'Disabled',
    device_restrictions: 'Device Restrictions',
    loading_restrictions: 'Loading restrictions...',
    allowed: 'Allowed',
    blocked: 'Blocked',
    no_devices_found: 'No devices found.',
    createUser: 'Create User',
    confirmDeletion: 'Confirm Deletion',
    users_confirm_delete:
      'Are you sure you want to delete user "{name}"? This action cannot be undone.',
    users_role_user_regular: 'User (Regular)',
    users_failed_load_restriction_details: 'Failed to load restriction details',
    users_failed_update_restriction: 'Failed to update restriction',
    users_toggle_restriction: 'Toggle restriction',
    example_username: 'e.g. jdoe',
    example_display_name: 'e.g. John Doe',
    example_email: 'e.g. john@example.com',
    inventory_subtitle: 'Manage your inbound stock and inventory records',
    inventory_request_submitted_success: 'Request submitted successfully',
    inventory_no_changes: 'No changes to submit',
    inventory_under_review_wait: 'Under review. Please wait.',
    inventory_submitting_request: 'Submitting...',
    loading: 'Loading...',
    updateSuccess: 'Update Successful',
    login: 'Log in',
    signup: 'Sign up',
    confirmClearLogs: 'Are you sure you want to clear all logs?',
    clearLogsFailed: 'Failed to clear logs',
    searchLogs: 'Search logs',
    clearLogs: 'Clear logs',
    docs: 'Docs',
    docsTitle: 'Appointer Docs',
    docsDescription: 'Learn how to make the most of Appointer. This page will contain documentation and guides about booking devices, managing reservations, and getting the best out of the system.',
    pending_review_back_to_login: 'Back to login',
    deviceList: 'Device List',
    selectDeviceToBook: 'Select a device to book',
    updateFailed: 'Update failed, please try again',
    deleteFailed: 'Delete failed, please try again',
    createDeviceSuccess: 'Device created successfully',
    createDeviceFailed: 'Failed to create device, please try again',
    back: 'Back',
    backToDeviceList: 'Back to devices',
    createDeviceSubtitle: 'Fill in device details and booking rules.',
    deviceNameLabel: 'Device name',
    deviceNamePlaceholder: 'e.g. Meeting Room A / Projector 01',
    deviceDescriptionLabel: 'Description',
    deviceDescriptionPlaceholder: 'Describe the device, location, or usage notes',
    bookingGranularityLabel: 'Time slot granularity',
    granularity30m: '30 min',
    granularity60m: '1 hour',
    granularity90m: '90 min',
    granularity120m: '2 hours',
    bookableDaysLabel: 'Bookable days',
    bookableEveryday: 'Every day',
    bookableSpecificWeekdays: 'Specific weekdays',
    selectWeekdaysLabel: 'Select weekdays',
    bookableTimeRangeLabel: 'Bookable time range',
    bookable24Hours: '24 hours',
    bookableSpecificTimeRange: 'Specific time range',
    setTimeRangeLabel: 'Set time range',
    startTime: 'Start time',
    endTime: 'End time',
    today: 'Today',
    prevWeek: 'Previous week',
    nextWeek: 'Next week',
    gridView: 'Grid view',
    listView: 'List view',
    viewModeWeek: 'Week',
    viewModeDay: 'Day',
    viewModeMonth: 'Month',
    bookingSaved: 'Reservation saved',
    bookingUpdated: 'Reservation updated',
    bookingDeleted: 'Reservation deleted',
    undo: 'Undo',
    undoFailedRefresh: 'Undo failed. Please refresh and try again.',
    deleteFailedRefresh: 'Delete failed. Please refresh and try again.',
    slotAlreadyBookedRefresh: 'This time slot was booked by someone else. Please refresh and try again.',
    undoFailedSlotBooked: 'Undo failed: this time slot is already booked.',
    deviceNotFound: 'Device not found',
    untitled: '(Untitled)',
    myReservation: 'My reservation',
    reserved: 'Reserved',
    myReservationsTitle: 'My reservations',
    userReservationsTitle: 'User reservations',
    allDevices: 'All devices',
    filterDevice: 'Filter devices',
    cancelSelected: 'Cancel selected',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
    noReservations: 'You have no active reservations.',
    noReservationsForDevice: 'No reservations for this device.',
    unknownDevice: 'Unknown device',
    unknownUser: 'Unknown user',
    confirmCancelReservation: 'Are you sure you want to cancel this reservation?',
    cancelFailedRetry: 'Cancel failed, please try again',
    confirmBulkCancel: 'Cancel the selected {count} reservations?',
    bulkCancelFailedRetry: 'Bulk cancel failed, please try again',
    view: 'View',
    addNewDevice: 'Add new device',
    confirmCreate: 'Confirm create?',
    expandMenu: 'Expand menu',
    addTitlePlaceholder: 'Add title',
    eventTypeEvent: 'Event',
    eventTypeTask: 'Task',
    eventTypeBooking: 'Booking',
    newBadge: 'New',
    timezoneNoRepeat: 'Time zone · Does not repeat',
    addGuests: 'Add guests',
    addGoogleMeet: 'Add Google Meet video meeting',
    addLocation: 'Add location',
    addDescriptionPlaceholder: 'Add description or Google Drive attachments',
    busyDefaultPublicNotify: 'Busy · Default visibility · Notify 30 minutes before',
    moreOptions: 'More options',
    deleteEvent: 'Delete event',
    colorSelector: 'Color selector',
    newDevice: 'New Device',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
    bookNow: 'Book Now',
    delete: 'Delete',
    confirm: 'Confirm',
    deleteDevice: 'Delete Device',
    enterDeviceName: 'Enter device name',
    addDescription: 'Add description...',
    doubleClickInfo: 'Double click to edit',
    available: 'Available',
    unavailable: 'Unavailable',
    on: 'On',
    off: 'Off',
    week: '',
    commit: 'Commit',
    user_management: 'User Management',
    user_management_subtitle: 'Manage system users and access controls.',
    search_users: 'Search users...',
    expiry_date: 'Expiry Date',
    permanent: 'Permanent',
    leaderboard: 'Leaderboard',
    leaderboard_subtitle: 'Top contributors by total reservation hours. Keep up the good work!',
    rank: 'Rank',
    column_user: 'User',
    role: 'Role',
    total_duration: 'Total Duration',
    edit_user: 'Edit User',
    delete_user_confirm: 'Are you sure you want to delete this user?',
    unknownError: 'Unknown error',
    da_importLegacyTemplatesConfirm:
      'We found templates saved from an older version on this device. Import them to your account and enable multi-device sync?',
    da_loadTemplatesFailed: 'Failed to load templates: {error}',
    da_invalidVarPair: 'Invalid Var1/Var2 configuration',
    da_yColumnsRequired: 'Please select Y data from the preview header columns.',
    da_varPairBothOrNeither: 'Var1 and Var2 must both be empty or both filled.',
    da_varPairCellOrText:
      'Var1 and Var2 must both be cell refs (e.g. A1) or both be text (e.g. Vg). Do not mix.',
    da_extractImportCsvFirst: 'Please import at least one CSV file first.',
    da_extractInvalidConfig: 'Invalid configuration.',
    da_extractSetXStart: 'Please set X Data start cell (e.g. A2).',
    da_extractPreviewLoading:
      'Preview is still loading. Please wait a moment and try again.',
    da_extractSetXEndOrUseEnd:
      "Please set X Data end cell (e.g. A1408) or use 'End' to read until the last preview row.",
    da_extractXSameColumn: 'X Data start/end must be in the same column.',
    da_extractInvalidXRange: 'Invalid X row range.',
    da_extractPointsCellPositiveInt:
      'Points cell {cell} must contain a positive integer.',
    da_extractPointsCellTooLarge:
      'Points from {cell} ({points}) cannot be larger than the X range length ({total}).',
    da_extractXNotDivisibleByPoints:
      'X range has {total} points, which is not divisible by points={points}.',
    da_extractXPointsPositiveIntOrCell:
      'X Points must be a positive integer (or a cell like B2).',
    da_extractXPointsTooLarge:
      'X Points ({points}) cannot be larger than the X range length ({total}).',
    da_extractXNotDivisibleByPointsFromCell:
      'X range has {total} points, which is not divisible by points={points} (from {cell}).',
    da_extractYStartEndValidCells:
      'Y Data start/end must be valid cells (e.g. B2 and D2).',
    da_extractSelectYColumn:
      'Please select at least one Y column (click column headers in the preview).',
    da_extractYCannotIncludeX: 'Y columns cannot include the X column.',
    da_extractYLegendStartCellRequired:
      'Y Data Start must be a valid cell (e.g. D1) when using Count/Step for legends.',
    da_extractYCountPositiveIntOrCell:
      'Y Data Count must be a positive integer (or a cell like B2).',
    da_extractYStepPositiveNumberOrCell:
      'Y Data Step must be a positive number (or a cell like B2).',
    da_extractYCountCellPositiveInt:
      'Y Data Count cell {cell} must contain a positive integer.',
    da_extractYStepCellPositiveNumber:
      'Y Data Step cell {cell} must contain a positive number.',
    da_template_saved: 'Template saved',
  },
  zh: {
    da_extract_started: '开始提取 {count} 个文件（{detail}{groups}）。图表将逐步显示。{warnings}',
    da_extract_started_incremental:
      '开始提取 {count} 个新增文件（{detail}{groups}）。图表将逐步显示。{warnings}',
    da_extract_points_from_cell: '点数来自 {cell}',
    da_extract_points_fixed: '点数={points}',
    da_extract_groups_suffix: '，{groups} 组',
    da_extract_warnings_block: '\n\n警告：\n- {warnings}',
    bg_scale_compare_title: '背景色阶色卡',
    bg_scale_compare_desc: '预览当前 Tailwind token 与暖白建议色阶。',
    bg_scale_compare_current: '当前（Tailwind token）',
    bg_scale_compare_proposed_warm: '建议（暖白 0–500）',
    typography_demo_title: 'Typography Demo',
    typography_demo_desc: 'Preview the project type scale (families + sizes). Numbers are Tailwind defaults unless overridden.',
    card_demo_title: 'Card Demo',
    card_demo_desc:
      '在 DevTools 检查 Card 根元素：`data-cta*` / `id` / `aria-label`。',
    card_demo_marker: '标记文本（子内容）',
    card_demo_default: '默认（default）',
    card_demo_panel: '面板（panel）',
    card_demo_flat: '扁平（flat）',
    card_demo_glass: '玻璃（glass）',
    card_demo_default_aria: 'Card 示例：默认',
    card_demo_panel_aria: 'Card 示例：面板',
    card_demo_flat_aria: 'Card 示例：扁平',
    card_demo_glass_aria: 'Card 示例：玻璃',
    journal_links: '期刊链接',
    literature_status_ready: '就绪',
    literature_source_nature: 'Nature',
    literature_source_science: 'Science',
    literature_source_acs: 'ACS',
    literature_source_wiley: 'Wiley',
    literature_source_unsupported: '不支持',
    literature_seed_url_placeholder: '文章链接',
    literature_seed_title_placeholder: '标题',
    literature_max_results_invalid: '最大返回条数必须是数字。',
    settings: '设置',
    appearance: '外观',
    language: '语言',
    profile: '个人资料',
    security: '账号安全',
    dataRetention: '数据保留',
    retentionHint: '按条数上限保留日志：超过上限会自动删除最早的记录。',
    logsMaxCount: '日志保留上限（条）',
    logsRetentionDays: '日志保留天数',
    requestsRetentionDays: '消息保留天数',
    lastCleanupAt: '上次裁剪时间',
    nextCleanupAt: '下次计划清理时间',
    runCleanupNow: '立即裁剪',
    retentionLoadFailed: '加载保留策略失败',
    retentionCleanupFailed: '执行清理失败',
    passwordMismatch: '两次输入的密码不一致',
    light: '浅色',
    dark: '深色',
    system: '跟随系统',
    changeAvatar: '更换头像',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    saveChanges: '保存',
    dashboard: '仪表盘',
    overview: '预约概览',
    device_analysis: '器件分析',
    device_analysis_subtitle: '导入、提取并可视化器件数据',
    da_import_section: '数据导入',
    da_import: '数据导入',
    da_import_csv: '导入 CSV',
    da_csv_empty_title: '\u4e0a\u4f20 CSV \u6587\u4ef6',
    da_csv_empty_subtitle_prefix: '\u62d6\u62fd\u6587\u4ef6\u5230\u8fd9\u91cc\u6216',
    da_csv_empty_browse: '\u6d4f\u89c8',
    da_loaded_csv_files: '已加载 {count} 个 CSV 文件',
    da_reset_session: '重置会话',
    da_extraction_errors: '提取错误',
    da_data_extraction_template: '数据提取',
    da_apply_to_all_files: '应用到所有',
    da_apply_to_new_files: '仅新增文件',
    da_apply_to_new_files_busy: '正在提取中，请稍后。',
    da_apply_to_new_files_no_new: '没有需要新增提取的文件。',
    da_apply_to_new_files_requires_full_apply: '请先点击“应用到所有”。',
    da_apply_to_new_files_requires_same_config: '模板配置已变更，请重新“应用到所有”。',
    da_stop_on_first_invalid_file: '首个无效即停止',
    da_save_template: '保存模板',
    da_template_discard_changes_title: '放弃修改？',
    da_template_discard_changes_desc:
      '你在“保存”面板有未保存的修改。要放弃这些修改并返回“选择”吗？',
    da_template_discard_changes_keep_editing: '继续编辑',
    da_template_discard_changes_discard: '放弃修改',
    da_new_template: '新建模板',
    da_delete_template: '删除模板',
    da_no_saved_templates: '暂无已保存模板',
    da_template_name: '模板名称',
    da_general_template: '通用模板',
    da_template_mode: '模板模式',
    da_template_mode_select: '选择',
    da_template_mode_save: '保存',
    da_match_by_file_name: '按文件名匹配',
    da_analysis_visualization: '分析与可视化',
    da_view_table: '数据表',
    da_view_charts: '图表',
    da_no_processed_data: '暂无处理结果',
    da_no_processed_data_hint: '请先在上方应用模板以生成结果。',
    da_no_data_extracted: '尚未提取任何数据。',
    da_no_data_extracted_hint: '请先导入 CSV 并应用模板以查看结果。',
    da_no_file_selected: '未选择文件',
    da_preview_loading: '预览加载中...',
    da_preview_loading_hint: '正在解析 CSV 预览，请稍候。',
    da_preview_error: '预览加载失败',
    da_preview_error_hint: '请尝试重新选择该文件',
    da_preview_select_file_hint: '请选择文件以预览',
    da_preview_filename_label: '文件名',
    da_select_series: '选择序列',
    common_clear: '清除',
    common_close: '关闭',
    devices: '设备管理',
    booking: '设备预约',
    messages: '消息通知',
    literature_research: '文献调研',
    literature_research_title: '文献调研',
    literature_research_subtitle: '输入需要抓取的入口链接，按日期范围筛选并提取摘要。',
    literature_filters: '抓取参数',
    literature_filters_hint: '支持 Nature / Science（Science 通过 RSS + Crossref 获取摘要）',
    literature_fetching: '抓取中...',
    literature_fetch: '开始抓取',
    literature_seed_urls: '入口链接',
    literature_add_url: '添加链接',
    literature_remove_url: '移除',
    literature_seed_urls_hint: '提示：你可以直接粘贴 Science 的页面链接（如 /journal/sciadv），系统会自动映射为可抓取的 RSS。',
    literature_seed_urls_hint_nature: '提示：支持 Nature 及其子刊的 Research Articles 页面的 URL。',
    literature_seed_urls_hint_science: '提示：Science 抓取通过 RSS + Crossref 获取摘要，你可以直接粘贴栏目链接。',
    literature_start_date: '开始日期',
    literature_end_date: '截止日期',
    literature_max_results: '最大返回',
    literature_max_results_hint: '建议 ≤ 100',
    literature_results: '结果',
    literature_results_title: '检索结果',
    literature_keyword_matching: '关键词匹配',
    literature_results_count: '条',
    literature_no_results: '没有找到符合条件的文章',
    literature_no_results_hint: '尝试调整日期范围或入口链接。',
    literature_download: '下载',
    literature_download_unavailable: '无可下载文件',
    literature_no_abstract: '（该条目暂无摘要）',
    literature_translate: '翻译摘要（中文）',
    literature_show_translation: '查看中文翻译',
    literature_show_original: '查看原摘要',
    literature_translate_wait: '有摘要正在翻译，请稍候。',
    literature_translation_label: '翻译',
    literature_translation_label_en: '英文翻译',
    literature_translation_label_zh: '中文翻译',
    literature_translate_failed: '翻译失败。',
    literature_translation_failed_fallback: '（翻译失败，以下为原摘要）',
    literature_export_docx: '导出 DOCX',
    literature_export_docx_translating: '翻译中',
    literature_export_docx_building: '生成文档中...',
    literature_export_docx_success: 'DOCX 已导出。',
    literature_export_docx_failed: 'DOCX 导出失败。',
    literature_export_json: '导出 JSON',
    literature_export_json_success: 'JSON 已导出。',
    literature_export_json_missing_doi: 'JSON 导出已阻止：所选条目存在缺少 DOI 的文献。',
    literature_select_all_filtered: '全选',
    literature_deselect_all_filtered: '取消全选',
    literature_selected_count: '当前选中',
    literature_clear_selection: '清空选择',
    literature_select_item: '选择该条',
    literature_clear_session: '清空本页会话',
    literature_session_cleared: '本页会话已清空。',
    literature_translate_test_title: '翻译测试',
    literature_translate_test_hint: '翻译一段短文本，用于确认当前使用的是个人 Key 还是默认 Key。',
    literature_translate_test_placeholder: '粘贴一段英文摘要用于测试翻译...',
    literature_translate_test_required: '请先填写测试文本。',
    literature_translate_test_run: '测试翻译',
    literature_translate_test_running: '测试中...',
    translation_service: '翻译服务',
    literature_translate_test_used_key: '使用的 Key',
    literature_translate_test_key_user: '个人',
    literature_translate_test_key_default: '默认',
    literature_translate_test_key_none: '未配置',
    literature_translate_test_cached: '缓存',
    literature_translate_test_failed: '测试失败',
    literature_translate_effective_key_source: '当前生效的 Key',
    literature_translate_test_bypass_cache: '强制请求上游（不走缓存）',
    literature_translate_test_force_default: '使用默认 Key 测试（全局）',
    translation_provider: '翻译供应商',
    translation_provider_hint: '同一时间只启用一个供应商。',
    default_provider: '默认供应商（全局）',
    default_provider_hint: '未设置个人 Key/供应商时使用。',
    personal_provider: '个人供应商',
    personal_provider_hint: '与个人 Key 一起使用；留空则使用默认供应商。',
    provider_current: '当前供应商',
    personal_provider_using_default: '使用默认供应商',
    personal_provider_requires_personal_key:
      '为安全起见，个人供应商仅在设置个人 Key 时生效。',
    translation_provider_required: '请先填写供应商。',
    translation_provider_saved: '供应商已保存。',
    translation_provider_save_failed: '保存供应商失败。',
    translation_provider_cleared: '供应商已清除。',
    translation_provider_clear_failed: '清除供应商失败。',
    translation_provider_short: '供应商',
    translation_provider_switch_confirm: '切换翻译供应商会清空全局默认 Key/模型，是否继续？',
    translation_provider_updated: '翻译供应商已更新。',
    translation_provider_update_failed: '更新供应商失败。',
    translation_base_url_short: 'Base URL',
    translation_model_short: '模型',
    personal_api_key: '个人 API KEY',
    personal_api_key_hint:
      '仅用于个人，保存后不会完整显示',
    personal_api_key_placeholder: '在此粘贴 API Key...',
    personal_api_key_using_default: '当前使用默认 Key（管理员设置），可填写个人 Key 覆盖。',
    api_key_saved: '已保存的 Key',
    model_current: '当前模型',
    model_builtin: '内置',
    personal_model: '模型',
    personal_model_hint: '与个人 Key 一起使用，留空则使用默认模型。',
    personal_model_placeholder: '例如：glm-4.5-flash',
    personal_model_required: '请先填写模型名称。',
    personal_model_saved: '模型已保存。',
    personal_model_save_failed: '保存模型失败。',
    personal_model_cleared: '模型已清除。',
    personal_model_clear_failed: '清除模型失败。',
    personal_model_using_default: '当前使用默认模型。',
    personal_model_requires_personal_key:
      '为安全起见，个人模型仅在设置个人 Key 时生效。',
    default_api_key: '默认全局 API key',
    default_api_key_hint: '当用户未设置个人 Key 时使用。',
    default_api_key_placeholder: '在此粘贴默认 API Key...',
    default_model: '默认全局模型',
    default_model_hint: '与全局默认 Key 一起使用。',
    default_model_placeholder: '例如：glm-4.5-flash',
    default_model_required: '请先填写默认模型名称。',
    default_model_saved: '默认模型已保存。',
    default_model_save_failed: '保存默认模型失败。',
    default_model_cleared: '默认模型已清除。',
    default_model_clear_failed: '清除默认模型失败。',
    default_api_key_required: '请先填写默认 API Key。',
    default_api_key_saved: '默认 API Key 已保存。',
    default_api_key_save_failed: '保存默认 API Key 失败。',
    default_api_key_cleared: '默认 API Key 已清除。',
    default_api_key_clear_failed: '清除默认 API Key 失败。',
    literature_save: '保存',
    literature_clear: '清除',
    literature_saving: '保存中...',
    personal_api_key_required: '请先填写 API Key。',
    personal_api_key_saved: 'API Key 已保存。',
    personal_api_key_save_failed: '保存 API Key 失败。',
    personal_api_key_cleared: 'API Key 已清除。',
    personal_api_key_clear_failed: '清除 API Key 失败。',
    literature_use_examples: '填充示例链接',
    literature_seed_urls_required:
      '请至少勾选一个入口链接（仅支持 nature.com / science.org / pubs.acs.org / *.onlinelibrary.wiley.com，可跨 Nature/Science/ACS/Wiley）。',
    literature_settings_loading: '设置读取中...',
    literature_settings_saving: '设置同步中...',
    literature_settings_saved: '设置已同步',
    literature_settings_save_failed: '设置同步失败',
    literature_settings_save_failed_fetch_continues:
      '设置同步失败，将使用当前输入继续抓取。',
    literature_keyword_filter: '关键词筛选',
    literature_keyword_filter_hint: '检索完成后在本地筛选，可切换查看“未匹配”以检查是否存在遗漏。',
    literature_match_any: '任意匹配',
    literature_match_all: '全部匹配',
    literature_clear_keywords: '清空关键词',
    literature_keywords_placeholder: '关键词匹配：two-dimensional, wafer, AI 等（用空格/换行/逗号分隔）',
    literature_keywords_count: '当前关键词',
    literature_view_all: '全部',
    literature_view_matched: '匹配',
    literature_view_unmatched: '未匹配',
    literature_sort: '排序',
    literature_sort_source: '抓取顺序',
    literature_sort_date: '按日期',
    literature_order_warning_rss_fallback:
      '当前使用 RSS 抓取顺序（Wiley 页面 HTML 无法抓取），结果可能顺序不一致或有遗漏。',
    literature_order_warning_rss_fallback_blocked:
      'Wiley 页面可能被 Cloudflare 拦截，当前显示 RSS 抓取顺序，结果可能顺序不一致或有遗漏。',
    chinese: '中文',
    english: '英文',
    inventory: '入库单',
    request: '请求',
    requestUser: '请求用户',
    note: '备注',
    requestModification: '申请修改',
    contactAdmin: '请联系管理员修改此条目。',
    inventory_new_item: '新增入库项',
    inventory_modification: '入库修改',
    requested_by: '申请人：{name}',
    student_id: '学号',
    common_not_provided: '未提供',
    inventory_item_details: '条目详情',
    inventory_changes: '修改内容',
    inventory_changes_breakdown: '修改明细',
    inventory_field: '字段',
    inventory_original: '原值',
    inventory_new_value: '更改为',
    quantity: '数量',
    actions: '操作',
    addItem: '添加入库',
    edit: '编辑',
    cancel: '取消',
    category: '类别',
    itemName: '入库项',
    applicant: '申请人',
    inventoryList: '入库单',
    date: '日期',
    status: '状态',
    reviewing: '审核中',
    rejected: '已拒绝',
    approved: '已通过',
    exampleItemName: '例如：iPhone 15',
    exampleCategory: '例如：电子产品',
    welcomeBack: '欢迎回来',
    upcomingReservations: '即将到来的预约',
    reservedHours: '已预约时长',
    hours: '小时',
    completed: '已完成',
    recentActivity: '活动通知',
    noActivity: '暂无最近活动',
    noPendingRequests: '暂无待处理请求',
    confirmApproveAll: '确认全部同意？',
    approveAll: '同意',
    approveAllSuccess: '已全部同意。',
    approveAllFailed: '全部同意失败。',
    dashboard_tab_pending: '待审核',
    dashboard_tab_reviewed: '已审核',
    dashboard_no_reviewed_requests: '暂无已审核请求',
    dashboard_clear_reviewed: '清空已审核',
    dashboard_confirm_clear_reviewed: '确定要清空已审核记录吗？',
    dashboard_clear_reviewed_success: '已清空已审核记录',
    dashboard_clear_reviewed_failed: '清空已审核记录失败',
    systemUser: '系统',
    inventory_request_submitted_success: '申请已提交',
    inventory_no_changes: '未检测到修改，无需提交申请',
    inventory_under_review_wait: '审核中，请等待',
    inventory_submitting_request: '提交中...',
    dashboard_approve: '同意',
    dashboard_reject: '拒绝',
    dashboard_user_approved_success: '用户审批通过',
    dashboard_request_approved_success: '请求已审批通过',
    dashboard_failed_approve: '审批失败',
    dashboard_processing: '处理中...',
    dashboard_confirm_reject_user: '确定要拒绝该账号申请吗？',
    dashboard_confirm_reject_request: '确定要拒绝该请求吗？',
    dashboard_rejected_success: '已拒绝',
    dashboard_failed_reject: '拒绝失败',
    dashboard_confirm_revoke_request: '确定要撤销该请求吗？',
    dashboard_revoke: '撤销',
    dashboard_request_revoked_success: '请求已撤销',
    dashboard_failed_revoke_request: '撤销请求失败',
    dashboard_revoke_request: '撤销申请',
    dashboard_application_details: '申请详情',
    dashboard_request_details: '消息详情',
    createDevice: '创建设备',
    createReservation: '创建预约',
    registerUser: '新用户注册',
    logout: '退出登录',
    super_admin: '超级管理员',
    admin: '管理员',
    user: '用户',
    SUPER_ADMIN: '超级管理员',
    ADMIN: '管理员',
    USER: '用户',
    displayName: '显示名称',
    updateSuccess: '更新成功',
    login: '登录',
    signup: '注册',
    confirmClearLogs: '您确定要清空所有日志记录吗？',
    clearLogsFailed: '清空日志失败',
    searchLogs: '搜索日志',
    clearLogs: '清空日志',
    docs: '文档',
    docsTitle: 'Appointer 文档',
    docsDescription: '了解如何充分利用 Appointer。本页面包含有关设备预约、管理预约以及如何最大限度利用系统的文档和指南。',
    pending_review_back_to_login: '返回登录',
    deviceList: '设备列表',
    selectDeviceToBook: '选择设备进行预约',
    updateFailed: '更新失败，请重试',
    deleteFailed: '删除失败，请重试',
    createDeviceSuccess: '设备创建成功',
    createDeviceFailed: '创建设备失败，请重试',
    back: '返回',
    backToDeviceList: '返回设备列表',
    createDeviceSubtitle: '填写设备信息并设置预约规则',
    deviceNameLabel: '设备名称',
    deviceNamePlaceholder: '例如：会议室 A / 投影仪 01',
    deviceDescriptionLabel: '设备描述',
    deviceDescriptionPlaceholder: '简要描述设备的功能、位置或使用说明',
    bookingGranularityLabel: '预约时间粒度',
    granularity30m: '30分钟',
    granularity60m: '1小时',
    granularity90m: '90分钟',
    granularity120m: '2小时',
    bookableDaysLabel: '可预约日期',
    bookableEveryday: '每天可预约',
    bookableSpecificWeekdays: '特定星期可预约',
    selectWeekdaysLabel: '选择可预约的星期',
    bookableTimeRangeLabel: '可预约时间段',
    bookable24Hours: '24小时可预约',
    bookableSpecificTimeRange: '特定时间段可预约',
    setTimeRangeLabel: '设置时间段',
    startTime: '开始时间',
    endTime: '结束时间',
    today: '今天',
    prevWeek: '上一周',
    nextWeek: '下一周',
    gridView: '网格视图',
    listView: '列表视图',
    viewModeWeek: '周',
    viewModeDay: '日',
    viewModeMonth: '月',
    bookingSaved: '预约已保存',
    bookingUpdated: '预约已更新',
    bookingDeleted: '预约已删除',
    undo: '撤销',
    undoFailedRefresh: '撤销失败，请刷新后重试',
    deleteFailedRefresh: '删除失败，请刷新后重试',
    slotAlreadyBookedRefresh: '该时间段已被其他人预约，请刷新后重试',
    undoFailedSlotBooked: '撤销失败：该时间段已被其他人预约',
    deviceNotFound: '未找到设备',
    untitled: '（无标题）',
    myReservation: '我的预约',
    reserved: '已预约',
    myReservationsTitle: '我的预约',
    userReservationsTitle: '用户预约',
    allDevices: '全部设备',
    filterDevice: '筛选设备',
    cancelSelected: '取消选中',
    selectAll: '全选',
    deselectAll: '取消全选',
    noReservations: '您当前没有有效的预约。',
    noReservationsForDevice: '该设备下没有预约记录。',
    unknownDevice: '未知设备',
    unknownUser: '未知用户',
    confirmCancelReservation: '您确定要取消此预约吗？',
    cancelFailedRetry: '取消失败，请重试',
    confirmBulkCancel: '确定要取消选中的 {count} 个预约吗？',
    bulkCancelFailedRetry: '批量取消失败，请重试',
    view: '查看',
    addNewDevice: '添加新设备',
    confirmCreate: '确认创建?',
    expandMenu: '展开菜单',
    addTitlePlaceholder: '添加标题',
    eventTypeEvent: '事件',
    eventTypeTask: '任务',
    eventTypeBooking: '预约安排',
    newBadge: '新',
    timezoneNoRepeat: '时区 · 不重复',
    addGuests: '添加邀请对象',
    addGoogleMeet: '添加 Google Meet 视频会议',
    addLocation: '添加地点',
    addDescriptionPlaceholder: '添加说明或Google 云端硬盘附件',
    busyDefaultPublicNotify: '忙碌 · 默认的公开范围 · 通知 30 分钟前',
    moreOptions: '更多选项',
    deleteEvent: '删除事件',
    colorSelector: '选择颜色',
    newDevice: '新设备',
    mon: '一',
    tue: '二',
    wed: '三',
    thu: '四',
    fri: '五',
    sat: '六',
    sun: '日',
    bookNow: '立即预约',
    delete: '删除',
    confirm: '确认',
    deleteDevice: '删除设备',
    enterDeviceName: '输入设备名称',
    addDescription: '添加描述...',
    doubleClickInfo: '双击编辑',
    available: '可用',
    unavailable: '不可用',
    on: '开',
    off: '关',
    week: '周',
    commit: '提交',
    user_management: '用户管理',
    user_management_subtitle: '管理系统用户和访问权限。',
    search_users: '搜索用户...',
    expiry_date: '有效期至',
    permanent: '永久有效',
    leaderboard: '排行榜',
    leaderboard_subtitle: '按总预约时长排名的贡献者。继续保持！',
    rank: '排名',
    column_user: '用户',
    role: '角色',
    total_duration: '总时长',
    edit_user: '编辑用户',
    username: '用户名',
    email: '邮箱',
    password: '密码',
    password_placeholder: '********',
    limited_time: '限时',
    account_expiry: '账号有效期',
    account_status: '账号状态',
    disabled: '禁用',
    device_restrictions: '设备限制',
    loading_restrictions: '正在加载限制...',
    allowed: '允许',
    blocked: '已屏蔽',
    no_devices_found: '未找到设备。',
    createUser: '创建用户',
    confirmDeletion: '确认删除',
    users_confirm_delete: '确定要删除用户“{name}”吗？此操作不可撤销。',
    users_role_user_regular: '用户',
    users_failed_load_restriction_details: '加载限制详情失败',
    users_failed_update_restriction: '更新限制失败',
    users_toggle_restriction: '切换限制',
    example_username: '例如 jdoe',
    example_display_name: '例如 张三',
    example_email: '例如 john@example.com',
    inventory_subtitle: '管理入库库存与记录',
    loading: '加载中...',
    delete_user_confirm: '您确定要删除此用户吗？',
    unknownError: '未知错误',
    da_importLegacyTemplatesConfirm:
      '检测到旧版本的本地模板，是否导入到当前账号并开启多设备同步？',
    da_loadTemplatesFailed: '模板加载失败：{error}',
    da_invalidVarPair: 'Var1/Var2 配置不合法',
    da_yColumnsRequired: '请从预览表头中选择 Y 数据列。',
    da_varPairBothOrNeither: 'Var1 和 Var2 必须同时留空或同时填写。',
    da_varPairCellOrText:
      'Var1 和 Var2 只能同时使用单元格（如 A1）或同时使用文本（如 Vg），不允许混用。',
    da_extractImportCsvFirst: '请先导入至少一个 CSV 文件。',
    da_extractInvalidConfig: '配置不合法。',
    da_extractSetXStart: '请设置 X 数据起始单元格（例如 A2）。',
    da_extractPreviewLoading: '预览仍在加载中，请稍等后重试。',
    da_extractSetXEndOrUseEnd:
      "请设置 X 数据结束单元格（例如 A1408），或使用 'End' 读取到预览的最后一行。",
    da_extractXSameColumn: 'X 数据起止必须在同一列。',
    da_extractInvalidXRange: 'X 行范围不合法。',
    da_extractPointsCellPositiveInt: 'Points 单元格 {cell} 必须为正整数。',
    da_extractPointsCellTooLarge:
      'Points {cell} 的值（{points}）不能大于 X 范围长度（{total}）。',
    da_extractXNotDivisibleByPoints:
      'X 范围共有 {total} 个点，无法被 points={points} 整除。',
    da_extractXPointsPositiveIntOrCell: 'X Points 必须为正整数（或单元格如 B2）。',
    da_extractXPointsTooLarge:
      'X Points（{points}）不能大于 X 范围长度（{total}）。',
    da_extractXNotDivisibleByPointsFromCell:
      'X 范围共有 {total} 个点，无法被 points={points}（来自 {cell}）整除。',
    da_extractYStartEndValidCells: 'Y 数据起止必须为有效单元格（例如 B2 和 D2）。',
    da_extractSelectYColumn: '请至少选择一个 Y 列（点击预览表头列名）。',
    da_extractYCannotIncludeX: 'Y 列不能包含 X 列。',
    da_extractYLegendStartCellRequired:
      '使用 Count/Step 生成图例时，Y Data Start 必须为有效单元格（例如 D1）。',
    da_extractYCountPositiveIntOrCell: 'Y Data Count 必须为正整数（或单元格如 B2）。',
    da_extractYStepPositiveNumberOrCell: 'Y Data Step 必须为正数（或单元格如 B2）。',
    da_extractYCountCellPositiveInt: 'Y Data Count 单元格 {cell} 必须为正整数。',
    da_extractYStepCellPositiveNumber: 'Y Data Step 单元格 {cell} 必须为正数。',
    da_template_saved: '模板已保存',
    recentMessages: '消息通知',
    dashboard_applied_for_account: '\u8d26\u53f7\u7533\u8bf7',
    dashboard_inventory_request: '\u5e93\u5b58\u8bf7\u6c42',
    dashboard_user_col: '\u7528\u6237',
    dashboard_behavior: '\u884c\u4e3a',
    dashboard_inventory_create: '\u5e93\u5b58\u521b\u5efa',
    dashboard_inventory_update: '\u5e93\u5b58\u4fee\u6539',
    dashboard_activity_login_system: '\u767b\u5f55\u7cfb\u7edf',
    dashboard_activity_create_reservation: '\u521b\u5efa\u9884\u7ea6',
    dashboard_activity_cancel_reservation: '\u53d6\u6d88\u9884\u7ea6',
    dashboard_activity_literature_research: '\u6587\u732e\u8c03\u7814',
    dashboard_activity_reservation_timeout: '\u9884\u7ea6\u8d85\u65f6',
    dashboard_activity_create_device: '\u521b\u5efa\u8bbe\u5907',
    dashboard_activity_register_user: '\u6ce8\u518c\u7528\u6237',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return 'zh';
  });

  const t = (key, vars) => {
    const template = translations[language][key] || key;
    if (!vars || typeof template !== 'string') return template;

    return Object.entries(vars).reduce((acc, [varKey, value]) => {
      return acc.replaceAll(`{${varKey}}`, String(value));
    }, template);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
