import { useState, type ReactNode } from 'react';
import {
  LanguageContext,
  type LanguageCode,
  type TranslateFn,
  type TranslationVars,
} from './language-context';

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    common_clear: 'Clear',
    da_analysis_visualization: 'Analysis & Visualization',
    da_apply_to_all_files: 'Apply to All',
    da_apply_to_new_files: 'Apply to New',
    da_apply_to_new_files_busy: 'Extraction is already running.',
    da_apply_to_new_files_no_new: 'No new files to extract.',
    da_apply_to_new_files_requires_full_apply: 'Apply to All first.',
    da_apply_to_new_files_requires_same_config: 'Template changed. Please Apply to All again.',
    da_csv_empty_browse: 'browse',
    da_csv_empty_subtitle_prefix: 'Drag files here or',
    da_curveTaggingFileNameBothRequired: 'When using file-name tagging, please provide keywords for both Vg and Vd.',
    da_curveTaggingModeExclusive: 'Curve tagging must use either Var1/Var2 or file-name keywords, not both.',
    da_data_extraction_template: 'Data Extraction Template',
    da_delete_template: 'Delete template',
    da_extractImportCsvFirst: 'Please import at least one CSV file first.',
    da_extractInvalidConfig: 'Invalid configuration.',
    da_extractInvalidXRange: 'Invalid X row range.',
    da_extractPointsCellPositiveInt: 'Points cell {cell} must contain a positive integer.',
    da_extractPointsCellTooLarge: 'Points from {cell} ({points}) cannot be larger than the X range length ({total}).',
    da_extractCurveTypeUndeterminedFromVarHints: 'Unable to determine curve type from Var1/Var2 or nearby headers. Please check the template, or use file-name keywords.',
    da_extractPreviewLoading: 'Preview is still loading. Please wait a moment and try again.',
    da_extractSelectYColumn: 'Please select at least one Y column (click column headers in the preview).',
    da_extractSetXEndOrUseEnd: 'Please set X Data end cell (e.g. A1408) or use \'End\' to read until the last preview row.',
    da_extractSetXStart: 'Please set X Data start cell (e.g. A2).',
    da_extractXNotDivisibleByPoints: 'X range has {total} points, which is not divisible by points={points}.',
    da_extractXNotDivisibleByPointsFromCell: 'X range has {total} points, which is not divisible by points={points} (from {cell}).',
    da_extractXPointsPositiveIntOrCell: 'X Points must be a positive integer (or a cell like B2).',
    da_extractXPointsTooLarge: 'X Points ({points}) cannot be larger than the X range length ({total}).',
    da_extractXSameColumn: 'X Data start/end must be in the same column.',
    da_extractYCannotIncludeX: 'Y columns cannot include the X column.',
    da_extractYCountCellPositiveInt: 'Y Data Count cell {cell} must contain a positive integer.',
    da_extractYCountPositiveIntOrCell: 'Y Data Count must be a positive integer (or a cell like B2).',
    da_extractYStartEndValidCells: 'Y Data start/end must be valid cells (e.g. B2 and D2).',
    da_extractYStepCellPositiveNumber: 'Y Data Step cell {cell} must contain a positive number.',
    da_extractYStepPositiveNumberOrCell: 'Y Data Step must be a positive number (or a cell like B2).',
    da_extract_groups_suffix: ', {groups} group(s)',
    da_extract_points_fixed: 'points={points}',
    da_extract_points_from_cell: 'points from {cell}',
    da_extract_started: 'Extracting {count} file(s) ({detail}{groups}) to display charts. Will auto-switch to Analysis & Visualization when done.{warnings}',
    da_extract_started_incremental: 'Extracting {count} new file(s) ({detail}{groups}) to display charts. Will auto-switch to Analysis & Visualization when done.{warnings}',
    da_extract_warnings_block: '\n\nWarnings:\n- {warnings}',
    da_extraction_errors: 'Extraction errors',
    da_general_template: 'General Template',
    da_import: 'Data Import',
    da_import_csv: 'Import CSV',
    da_import_section: 'Import CSV files',
    da_menu_app: 'Device Analysis Studio',
    da_open_in_origin: 'Open in Origin',
    da_open_in_origin_success: 'Origin launched and import task submitted.',
    da_open_in_origin_batch_success: 'Origin import tasks submitted for {count} canvas(es).',
    da_open_in_origin_failed: 'Failed to open in Origin: {error}',
    da_open_in_origin_fallback_zip_success: 'Auto open failed. Exported ZIP + OGS package for manual import in Origin.',
    da_open_in_origin_fallback_zip_batch_success: 'Auto open failed. Exported ZIP + OGS package for {count} canvases.',
    da_open_in_origin_fallback_zip_failed: 'Auto open failed, and ZIP fallback export failed: {error}',
    da_origin_select_canvas: 'Please select at least one canvas first.',
    da_origin_canvas_label: 'Origin canvases',
    da_origin_canvas_selected_count: '{count} selected',
    da_origin_canvas_select_all: 'All',
    da_origin_canvas_select_current: 'Current only',
    da_origin_canvas_clear: 'Clear',
    da_origin_select_curve: 'Please select a curve first.',
    da_origin_pick_exe_required: 'Please select Origin executable path first.',
    da_origin_batch_pick_dir_required: 'Please choose a folder that contains CSV files first.',
    da_origin_error_stage: 'Stage: {stage}',
    da_origin_error_hresult: 'HRESULT: {hresult}',
    da_origin_error_log_path: 'Log: {path}',
    da_origin_error_tip_launch_once: 'Tip: launch Origin once manually, then retry.',
    da_origin_error_tip_register_com: 'Tip: run Origin once as administrator and register COM server (Origin.exe /regserver), then retry.',
    da_origin_error_tip_reselect_exe: 'Tip: reselect the correct Origin.exe path in Settings.',
    da_origin_error_tip_manual_zip: 'Tip: if auto open fails, export ZIP and run OGS manually in Origin.',
    da_origin_error_tip_install_python: 'Tip: install Python with pywin32 and ensure python/py is available in PATH.',
    da_origin_error_tip_batch_runner_missing: 'Tip: batch runner is missing. Keep Python runner for debugging, or include origin-batch-worker.exe for offline release.',
    da_origin_error_tip_batch_runner_check: 'Tip: check origin-batch-worker.exe path/permissions, or temporarily fall back to Python runner.',
    da_origin_error_tip_zip_runner_missing: 'Tip: ZIP runner is missing. Include origin-zip-worker.exe, or temporarily fall back to PowerShell worker script.',
    da_origin_error_tip_zip_runner_check: 'Tip: check origin-zip-worker.exe path/permissions, or temporarily fall back to PowerShell worker script.',
    da_origin_error_tip_choose_csv_folder: 'Tip: choose a folder that contains CSV files.',
    da_menu_export_zip: 'Export Analysis ZIP',
    da_menu_file: 'File',
    da_menu_help: 'Help',
    da_menu_import_csv: 'Import CSV',
    da_menu_language_en: 'Language: English',
    da_menu_language_zh: 'Language: Chinese',
    da_menu_page_back: 'Back',
    da_menu_page_forward: 'Forward',
    da_menu_page_analysis: 'Go to Analysis Page',
    da_menu_page_data: 'Go to Data Page',
    da_menu_reload_window: 'Reload Window',
    da_menu_reset_session: 'Reset Session',
    da_menu_shortcut_ctrl_o: 'Ctrl+O',
    da_menu_shortcut_ctrl_shift_e: 'Ctrl+Shift+E',
    da_menu_shortcut_f12: 'F12',
    da_menu_shortcut_f5: 'F5',
    da_menu_theme_dark: 'Theme: Dark',
    da_menu_theme_light: 'Theme: Light',
    da_menu_theme_system: 'Theme: System',
    da_menu_toggle_devtools: 'Toggle DevTools',
    da_menu_view: 'View',
    da_menu_window_close: 'Close Window',
    da_menu_window_maximize: 'Maximize / Restore',
    da_menu_window_minimize: 'Minimize Window',
    da_invalidVarPair: 'Invalid Var1/Var2 configuration',
    da_loadTemplatesFailed: 'Failed to load templates: {error}',
    da_loaded_csv_files: 'Loaded {count} CSV files',
    da_match_by_file_name: 'Match by file name',
    da_new_template: 'New template',
    da_analysis_processing: 'Processing analysis data...',
    da_analysis_processing_hint: 'Extracting and preparing chart data, please wait.',
    da_analysis_processing_progress: '{processed}/{total} files processed',
    da_analysis_loading: 'Loading analysis charts...',
    da_analysis_loading_hint: 'Preparing visualization modules, please wait.',
    da_no_processed_data: 'No Processed Data',
    da_no_processed_data_hint: 'Apply a template above to generate results.',
    da_no_saved_templates: 'No saved templates',
    da_preview_error: 'Preview failed to load',
    da_preview_error_hint: 'Please try selecting the file again.',
    da_preview_filename_label: 'Filename',
    da_preview_loading: 'Loading preview...',
    da_preview_loading_hint: 'Parsing CSV preview, please wait.',
    da_preview_select_file_hint: 'Select a file to preview',
    da_reset_session: 'Reset session',
    da_save_template: 'Save template',
    da_save_x_data_label: 'X data',
    da_save_y_data_label: 'Y data',
    da_save_start: 'Start',
    da_save_end: 'End',
    da_save_points: 'Points',
    da_save_curve_type: 'Curve type',
    da_save_var1: 'Var1',
    da_save_legend: 'Legend',
    da_save_var2: 'Var2',
    da_save_left_title: 'Left Title',
    da_save_var3: 'Var3',
    da_save_transfer: 'Transfer',
    da_save_output: 'Output',
    da_save_check_columns: 'Check columns',
    da_save_count: 'Points',
    da_save_step: 'Step',
    da_save_curve_tagging_conflict:
      'Var1/Var2 and file-name keywords cannot be used together. Please clear one.',
    da_settings_section_aria_label: 'Settings',
    da_settings_title: 'Settings',
    da_settings_language_title: 'Language',
    da_settings_language_desc: 'Switch the app language between Chinese and English.',
    da_settings_language_zh: '中文',
    da_settings_language_en: 'English',
    da_settings_storage_title: 'Data Persistence Path',
    da_settings_storage_desc: 'Configure where Device Analysis templates and settings are stored on disk.',
    da_settings_storage_path_label: 'Persistence Path',
    da_settings_storage_path_hint: 'Use an absolute file path.',
    da_settings_storage_not_configurable_hint: 'Path configuration is available in desktop app only.',
    da_settings_storage_loading: 'Loading...',
    da_settings_storage_unavailable: 'Persistence path unavailable.',
    da_settings_storage_load_failed: 'Failed to load persistence path: {error}',
    da_settings_storage_choose_path_btn: 'Choose Path',
    da_settings_storage_choose_saved: 'Persistence path updated.',
    da_settings_storage_choose_failed: 'Failed to update persistence path: {error}',
    da_settings_storage_save_btn: 'Save Path',
    da_settings_storage_reset_default_btn: 'Reset to Default',
    da_settings_storage_saved: 'Persistence path saved.',
    da_settings_storage_save_failed: 'Failed to save persistence path: {error}',
    da_settings_storage_reset_default_success: 'Persistence path reset to default.',
    da_settings_storage_reset_default_failed: 'Failed to reset persistence path: {error}',
    da_settings_storage_note: '',
    da_settings_origin_title: 'Origin Executable Path',
    da_settings_origin_desc: 'Configure the Origin executable used by "Open in Origin".',
    da_settings_origin_loading: 'Loading...',
    da_settings_origin_not_configurable_hint: 'Origin path configuration is available in Windows desktop app only.',
    da_settings_origin_choose_path_btn: 'Choose Origin.exe',
    da_settings_origin_choose_saved: 'Origin executable path updated.',
    da_settings_origin_choose_failed: 'Failed to update Origin executable path: {error}',
    da_settings_origin_check_btn: 'Check Connection',
    da_settings_origin_checking: 'Checking...',
    da_settings_origin_check_success: 'Origin connection check passed.',
    da_settings_origin_check_failed: 'Origin connection check failed: {error}',
    da_settings_origin_batch_desc: 'Batch process all CSV files (including subfolders) in a selected folder and auto-plot in Origin.',
    da_settings_origin_batch_btn: 'Run Folder Batch',
    da_settings_origin_batch_running: 'Batch running...',
    da_settings_origin_batch_success: 'Origin batch completed: {success}/{total} succeeded, {failed} failed.',
    da_settings_origin_batch_failed: 'Origin batch failed: {error}',
    da_settings_origin_plot_title: 'Default Plot Settings',
    da_settings_origin_plot_desc: 'Applied to Open in Origin and Python fallback plots in batch/zip jobs.',
    da_settings_origin_plot_type_label: 'Plot type',
    da_settings_origin_plot_type_200: '200 (Scatter)',
    da_settings_origin_plot_type_201: '201 (Line)',
    da_settings_origin_plot_type_202: '202 (Line + Symbol)',
    da_settings_origin_plot_xy_pairs_label: 'XY pairs',
    da_settings_origin_plot_xy_pairs_hint: 'LabTalk expression, for example ((1,2)) or ((1,2),(3,4)).',
    da_settings_origin_plot_command_label: 'Plot command override',
    da_settings_origin_plot_command_hint: 'Optional full LabTalk command. If set, it overrides plot type and XY pairs.',
    da_settings_origin_plot_post_commands_label: 'Post-plot commands',
    da_settings_origin_plot_post_commands_hint: 'One LabTalk command per line, executed after plotting.',
    da_settings_origin_plot_saved: 'Origin plot settings updated.',
    da_settings_origin_plot_save_failed: 'Failed to update plot settings: {error}',
    da_settings_origin_cleanup_title: 'Runtime Cleanup',
    da_settings_origin_cleanup_desc: 'Control auto-cleanup for Origin runtime jobs under .device/origin.',
    da_settings_origin_cleanup_enable_label: 'Auto cleanup',
    da_settings_origin_cleanup_enable_on: 'Enabled',
    da_settings_origin_cleanup_enable_off: 'Disabled',
    da_settings_origin_cleanup_keep_success_label: 'Keep successful jobs',
    da_settings_origin_cleanup_failed_days_label: 'Keep failed jobs (days)',
    da_settings_origin_cleanup_run_btn: 'Run Cleanup Now',
    da_settings_origin_cleanup_running: 'Cleaning...',
    da_settings_origin_cleanup_saved: 'Origin cleanup settings updated.',
    da_settings_origin_cleanup_save_failed: 'Failed to update cleanup settings: {error}',
    da_settings_origin_cleanup_run_success: 'Cleanup completed. Removed {count} job folder(s).',
    da_settings_origin_cleanup_run_failed: 'Cleanup failed: {error}',
    da_stop_on_first_invalid_file: 'Stop on first invalid file',
    da_overview_curve_filter_label: 'Curve filter',
    da_overview_curve_filter_all: 'All',
    da_overview_curve_filter_transfer: 'Transfer',
    da_overview_curve_filter_output: 'Output',
    da_overview_sort_ymax_title: 'Sort by yMax: {order}',
    da_overview_sort_ymax_none: 'None',
    da_overview_sort_ymax_desc: 'Descending',
    da_overview_sort_ymax_asc: 'Ascending',
    da_overview_processing: 'Processing {processed}/{total}',
    da_overview_select_mode_title: 'Canvas select mode: {state}',
    da_overview_select_mode_on: 'On',
    da_overview_select_mode_off: 'Off',
    da_overview_select_mode_toggle: 'Select',
    da_overview_select_badge: 'SELECT',
    da_overview_selected_num_figures: 'Selected {count} figures',
    da_tab_analysis: 'Analysis & Visualization',
    da_tab_data: 'Import & Extraction',
    da_tab_switcher_label: 'Device analysis page switcher',
    da_template_discard_changes_desc: 'You have unsaved edits in the Save panel. Discard them and return to Select?',
    da_template_discard_changes_discard: 'Discard changes',
    da_template_discard_changes_keep_editing: 'Keep editing',
    da_template_discard_changes_title: 'Discard changes?',
    da_template_mode: 'Template mode',
    da_template_mode_save: 'Save',
    da_template_mode_select: 'Select',
    da_template_name: 'Template name',
    da_template_saved: 'Template saved',
    da_varPairBothOrNeither: 'Var1 and Var2 must both be empty or both filled.',
    da_varPairCellOrText: 'Var1 and Var2 must both be cell refs (e.g. A1) or both be text (e.g. Vg). Do not mix.',
    da_yColumnsRequired: 'Please select Y data from the preview header columns.',
    unknownError: 'Unknown error',
  },
  zh: {
    common_clear: '清除',
    da_analysis_visualization: '分析与可视化',
    da_apply_to_all_files: '应用到所有',
    da_apply_to_new_files: '仅新增文件',
    da_apply_to_new_files_busy: '正在提取中，请稍后。',
    da_apply_to_new_files_no_new: '没有需要新增提取的文件。',
    da_apply_to_new_files_requires_full_apply: '请先点击“应用到所有”。',
    da_apply_to_new_files_requires_same_config: '模板配置已变更，请重新“应用到所有”。',
    da_csv_empty_browse: '浏览',
    da_csv_empty_subtitle_prefix: '拖拽文件到这里或',
    da_curveTaggingFileNameBothRequired: '使用文件名标注时，请同时填写 Vg 和 Vd 的关键词。',
    da_curveTaggingModeExclusive: '曲线标注方式只能二选一：使用 Var1/Var2 或使用文件名关键词，不能同时使用。',
    da_data_extraction_template: '数据提取',
    da_delete_template: '删除模板',
    da_extractImportCsvFirst: '请先导入至少一个 CSV 文件。',
    da_extractInvalidConfig: '配置不合法。',
    da_extractInvalidXRange: 'X 行范围不合法。',
    da_extractPointsCellPositiveInt: 'Points 单元格 {cell} 必须为正整数。',
    da_extractPointsCellTooLarge: 'Points {cell} 的值（{points}）不能大于 X 范围长度（{total}）。',
    da_extractCurveTypeUndeterminedFromVarHints: '无法根据 Var1/Var2 或附近表头判断曲线类型。请检查模板，或使用文件名关键字。',
    da_extractPreviewLoading: '预览仍在加载中，请稍等后重试。',
    da_extractSelectYColumn: '请至少选择一个 Y 列（点击预览表头列名）。',
    da_extractSetXEndOrUseEnd: '请设置 X 数据结束单元格（例如 A1408），或使用 \'End\' 读取到预览的最后一行。',
    da_extractSetXStart: '请设置 X 数据起始单元格（例如 A2）。',
    da_extractXNotDivisibleByPoints: 'X 范围共有 {total} 个点，无法被 points={points} 整除。',
    da_extractXNotDivisibleByPointsFromCell: 'X 范围共有 {total} 个点，无法被 points={points}（来自 {cell}）整除。',
    da_extractXPointsPositiveIntOrCell: 'X Points 必须为正整数（或单元格如 B2）。',
    da_extractXPointsTooLarge: 'X Points（{points}）不能大于 X 范围长度（{total}）。',
    da_extractXSameColumn: 'X 数据起止必须在同一列。',
    da_extractYCannotIncludeX: 'Y 列不能包含 X 列。',
    da_extractYCountCellPositiveInt: 'Y Data Count 单元格 {cell} 必须为正整数。',
    da_extractYCountPositiveIntOrCell: 'Y Data Count 必须为正整数（或单元格如 B2）。',
    da_extractYStartEndValidCells: 'Y 数据起止必须为有效单元格（例如 B2 和 D2）。',
    da_extractYStepCellPositiveNumber: 'Y Data Step 单元格 {cell} 必须为正数。',
    da_extractYStepPositiveNumberOrCell: 'Y Data Step 必须为正数（或单元格如 B2）。',
    da_extract_groups_suffix: '，{groups} 组',
    da_extract_points_fixed: '点数={points}',
    da_extract_points_from_cell: '点数来自 {cell}',
    da_extract_started: '提取 {count} 个文件（{detail}{groups}）以显示图表。完成后将自动跳转到分析与可视化页面。{warnings}',
    da_extract_started_incremental: '提取 {count} 个新增文件（{detail}{groups}）以显示图表。完成后将自动跳转到分析与可视化页面。{warnings}',
    da_extract_warnings_block: '\n\n警告：\n- {warnings}',
    da_extraction_errors: '提取错误',
    da_general_template: '通用模板',
    da_import: '数据导入',
    da_import_csv: '导入 CSV',
    da_import_section: '数据导入',
    da_menu_app: 'Device Analysis Studio',
    da_open_in_origin: '在 Origin 中打开',
    da_open_in_origin_success: '已唤起 Origin，并提交导入绘图任务。',
    da_open_in_origin_batch_success: '已向 Origin 提交 {count} 个 canvas 的导入绘图任务。',
    da_open_in_origin_failed: '在 Origin 中打开失败：{error}',
    da_open_in_origin_fallback_zip_success: '自动打开失败，已导出 ZIP + OGS 包，请在 Origin 中手动导入。',
    da_open_in_origin_fallback_zip_batch_success: '自动打开失败，已导出 {count} 个 canvas 的 ZIP + OGS 包，请在 Origin 中手动导入。',
    da_open_in_origin_fallback_zip_failed: '自动打开失败，且导出 ZIP 回退包失败：{error}',
    da_origin_select_canvas: '请先选择至少一个 canvas。',
    da_origin_canvas_label: 'Origin 画布',
    da_origin_canvas_selected_count: '已选 {count} 个',
    da_origin_canvas_select_all: '全选',
    da_origin_canvas_select_current: '仅当前',
    da_origin_canvas_clear: '清空',
    da_origin_select_curve: '请先选择一条曲线。',
    da_origin_pick_exe_required: '请先配置 Origin 可执行文件路径。',
    da_origin_batch_pick_dir_required: '\u8bf7\u5148\u9009\u62e9\u4e00\u4e2a\u5305\u542b CSV \u7684\u6587\u4ef6\u5939\u3002',
    da_origin_error_stage: '\u9636\u6bb5\uff1a{stage}',
    da_origin_error_hresult: 'HRESULT\uff1a{hresult}',
    da_origin_error_log_path: '\u65e5\u5fd7\uff1a{path}',
    da_origin_error_tip_launch_once: '\u5efa\u8bae\uff1a\u5148\u624b\u52a8\u542f\u52a8\u4e00\u6b21 Origin\uff0c\u518d\u91cd\u8bd5\u3002',
    da_origin_error_tip_register_com: '\u5efa\u8bae\uff1a\u4ee5\u7ba1\u7406\u5458\u8fd0\u884c\u4e00\u6b21 Origin\uff0c\u6267\u884c COM \u6ce8\u518c\uff08Origin.exe /regserver\uff09\u540e\u518d\u91cd\u8bd5\u3002',
    da_origin_error_tip_reselect_exe: '\u5efa\u8bae\uff1a\u5728\u8bbe\u7f6e\u4e2d\u91cd\u65b0\u9009\u62e9\u6b63\u786e\u7684 Origin.exe \u8def\u5f84\u3002',
    da_origin_error_tip_manual_zip: '\u5efa\u8bae\uff1a\u81ea\u52a8\u6253\u5f00\u5931\u8d25\u65f6\uff0c\u6539\u7528 ZIP + OGS \u624b\u52a8\u5bfc\u5165\u3002',
    da_origin_error_tip_install_python: '\u5efa\u8bae\uff1a\u5b89\u88c5 Python \u4e0e pywin32 \uff0c\u5e76\u786e\u4fdd PATH \u4e2d\u53ef\u7528 python/py\u3002',
    da_origin_error_tip_batch_runner_missing: '\u5efa\u8bae\uff1a\u672a\u627e\u5230\u6279\u5904\u7406\u6267\u884c\u5668\u3002\u8c03\u8bd5\u9636\u6bb5\u4fdd\u7559 Python \u8fd0\u884c\u5668\uff0c\u79bb\u7ebf\u53d1\u5e03\u65f6\u518d\u5185\u7f6e origin-batch-worker.exe\u3002',
    da_origin_error_tip_batch_runner_check: '\u5efa\u8bae\uff1a\u68c0\u67e5 origin-batch-worker.exe \u8def\u5f84/\u6743\u9650\uff0c\u6216\u6682\u65f6\u56de\u9000\u5230 Python \u8fd0\u884c\u5668\u3002',
    da_origin_error_tip_zip_runner_missing: '\u5efa\u8bae\uff1a\u672a\u627e\u5230 ZIP \u6267\u884c\u5668\u3002\u53d1\u5e03\u65f6\u8bf7\u5185\u7f6e origin-zip-worker.exe\uff0c\u6216\u6682\u65f6\u56de\u9000\u5230 PowerShell \u6267\u884c\u811a\u672c\u3002',
    da_origin_error_tip_zip_runner_check: '\u5efa\u8bae\uff1a\u68c0\u67e5 origin-zip-worker.exe \u8def\u5f84/\u6743\u9650\uff0c\u6216\u6682\u65f6\u56de\u9000\u5230 PowerShell \u6267\u884c\u811a\u672c\u3002',
    da_origin_error_tip_choose_csv_folder: '\u5efa\u8bae\uff1a\u9009\u62e9\u5305\u542b CSV \u6587\u4ef6\u7684\u6587\u4ef6\u5939\u3002',
    da_menu_export_zip: '导出分析压缩包',
    da_menu_file: '文件',
    da_menu_help: '帮助',
    da_menu_import_csv: '导入 CSV',
    da_menu_language_en: '语言：英文',
    da_menu_language_zh: '语言：中文',
    da_menu_page_back: '后退',
    da_menu_page_forward: '前进',
    da_menu_page_analysis: '切换到分析页',
    da_menu_page_data: '切换到数据页',
    da_menu_reload_window: '重新加载窗口',
    da_menu_reset_session: '重置会话',
    da_menu_shortcut_ctrl_o: 'Ctrl+O',
    da_menu_shortcut_ctrl_shift_e: 'Ctrl+Shift+E',
    da_menu_shortcut_f12: 'F12',
    da_menu_shortcut_f5: 'F5',
    da_menu_theme_dark: '主题：深色',
    da_menu_theme_light: '主题：浅色',
    da_menu_theme_system: '主题：跟随系统',
    da_menu_toggle_devtools: '切换开发者工具',
    da_menu_view: '视图',
    da_menu_window_close: '关闭窗口',
    da_menu_window_maximize: '最大化 / 还原',
    da_menu_window_minimize: '最小化窗口',
    da_invalidVarPair: 'Var1/Var2 配置不合法',
    da_loadTemplatesFailed: '模板加载失败：{error}',
    da_loaded_csv_files: '已加载 {count} 个 CSV 文件',
    da_match_by_file_name: '按文件名匹配',
    da_new_template: '新建模板',
    da_analysis_processing: '分析数据处理中...',
    da_analysis_processing_hint: '正在提取并准备图表数据，请稍候。',
    da_analysis_processing_progress: '已处理 {processed}/{total} 个文件',
    da_analysis_loading: '\u5206\u6790\u56fe\u8868\u52a0\u8f7d\u4e2d...',
    da_analysis_loading_hint: '\u6b63\u5728\u51c6\u5907\u53ef\u89c6\u5316\u6a21\u5757\uff0c\u8bf7\u7a0d\u5019\u3002',
    da_no_processed_data: '暂无处理结果',
    da_no_processed_data_hint: '请先在上方应用模板以生成结果。',
    da_no_saved_templates: '暂无已保存模板',
    da_preview_error: '预览加载失败',
    da_preview_error_hint: '请尝试重新选择该文件',
    da_preview_filename_label: '文件名',
    da_preview_loading: '预览加载中...',
    da_preview_loading_hint: '正在解析 CSV 预览，请稍候。',
    da_preview_select_file_hint: '请选择文件以预览',
    da_reset_session: '重置会话',
    da_save_template: '保存模板',
    da_save_x_data_label: '\u0058 \u6570\u636e',
    da_save_y_data_label: '\u0059 \u6570\u636e',
    da_save_start: '\u5f00\u59cb',
    da_save_end: '\u7ed3\u675f',
    da_save_points: '\u70b9\u6570',
    da_save_curve_type: '\u66f2\u7ebf\u7c7b\u578b',
    da_save_var1: 'Var1',
    da_save_legend: '\u56fe\u4f8b',
    da_save_var2: 'Var2',
    da_save_left_title: '\u7eb5\u6807\u9898',
    da_save_var3: 'Var3',
    da_save_transfer: '\u8f6c\u79fb',
    da_save_output: '\u8f93\u51fa',
    da_save_check_columns: '\u52fe\u9009\u5217',
    da_save_count: '\u70b9\u6570',
    da_save_step: '\u6b65\u957f',
    da_save_curve_tagging_conflict:
      '\u0056\u0061\u0072\u0031\u002f\u0056\u0061\u0072\u0032 \u4e0e\u6587\u4ef6\u540d\u5173\u952e\u8bcd\u4e0d\u80fd\u540c\u65f6\u4f7f\u7528\uff0c\u8bf7\u6e05\u7a7a\u5176\u4e2d\u4e00\u7ec4\u3002',
    da_settings_section_aria_label: '设置',
    da_settings_title: '设置',
    da_settings_language_title: '\u8bed\u8a00',
    da_settings_language_desc: '\u5728\u4e2d\u6587\u4e0e English \u4e4b\u95f4\u5207\u6362\u754c\u9762\u8bed\u8a00\u3002',
    da_settings_language_zh: '\u4e2d\u6587',
    da_settings_language_en: 'English',
    da_settings_storage_title: '数据持久化路径',
    da_settings_storage_desc: '配置 Device Analysis 模板和设置在本地磁盘的存储位置。',
    da_settings_storage_path_label: '持久化路径',
    da_settings_storage_path_hint: '请输入绝对文件路径。',
    da_settings_storage_not_configurable_hint: '仅桌面版应用支持路径配置。',
    da_settings_storage_loading: '加载中...',
    da_settings_storage_unavailable: '持久化路径暂不可用。',
    da_settings_storage_load_failed: '加载持久化路径失败：{error}',
    da_settings_storage_choose_path_btn: '选择路径',
    da_settings_storage_choose_saved: '持久化路径已更新。',
    da_settings_storage_choose_failed: '更新持久化路径失败：{error}',
    da_settings_storage_save_btn: '保存路径',
    da_settings_storage_reset_default_btn: '恢复默认',
    da_settings_storage_saved: '持久化路径已保存。',
    da_settings_storage_save_failed: '保存持久化路径失败：{error}',
    da_settings_storage_reset_default_success: '已恢复为默认持久化路径。',
    da_settings_storage_reset_default_failed: '恢复默认持久化路径失败：{error}',
    da_settings_storage_note: '',
    da_settings_origin_title: '\u004f\u0072\u0069\u0067\u0069\u006e\u0020\u53ef\u6267\u884c\u6587\u4ef6\u8def\u5f84',
    da_settings_origin_desc: '\u914d\u7f6e\u201c\u5728\u0020\u004f\u0072\u0069\u0067\u0069\u006e\u0020\u4e2d\u6253\u5f00\u201d\u6240\u4f7f\u7528\u7684\u0020\u004f\u0072\u0069\u0067\u0069\u006e\u0020\u53ef\u6267\u884c\u6587\u4ef6\u3002',
    da_settings_origin_loading: '\u52a0\u8f7d\u4e2d\u002e\u002e\u002e',
    da_settings_origin_not_configurable_hint: '\u4ec5\u0020\u0057\u0069\u006e\u0064\u006f\u0077\u0073\u0020\u684c\u9762\u7248\u5e94\u7528\u652f\u6301\u0020\u004f\u0072\u0069\u0067\u0069\u006e\u0020\u8def\u5f84\u914d\u7f6e\u3002',
    da_settings_origin_choose_path_btn: '\u9009\u62e9\u0020\u004f\u0072\u0069\u0067\u0069\u006e\u002e\u0065\u0078\u0065',
    da_settings_origin_choose_saved: '\u004f\u0072\u0069\u0067\u0069\u006e\u0020\u53ef\u6267\u884c\u6587\u4ef6\u8def\u5f84\u5df2\u66f4\u65b0\u3002',
    da_settings_origin_choose_failed: '\u66f4\u65b0\u0020\u004f\u0072\u0069\u0067\u0069\u006e\u0020\u53ef\u6267\u884c\u6587\u4ef6\u8def\u5f84\u5931\u8d25\uff1a\u007b\u0065\u0072\u0072\u006f\u0072\u007d',
    da_settings_origin_check_btn: '\u68c0\u67e5\u8fde\u63a5',
    da_settings_origin_checking: '\u68c0\u67e5\u4e2d...',
    da_settings_origin_check_success: 'Origin \u8fde\u63a5\u68c0\u67e5\u901a\u8fc7\u3002',
    da_settings_origin_check_failed: 'Origin \u8fde\u63a5\u68c0\u67e5\u5931\u8d25\uff1a{error}',
    da_settings_origin_batch_desc: '\u6279\u91cf\u5904\u7406\u6240\u9009\u6587\u4ef6\u5939\uff08\u542b\u5b50\u76ee\u5f55\uff09\u4e0b\u7684\u5168\u90e8 CSV \uff0c\u5e76\u5728 Origin \u4e2d\u81ea\u52a8\u7ed8\u56fe\u3002',
    da_settings_origin_batch_btn: '\u8fd0\u884c\u6587\u4ef6\u5939\u6279\u5904\u7406',
    da_settings_origin_batch_running: '\u6279\u5904\u7406\u8fd0\u884c\u4e2d...',
    da_settings_origin_batch_success: 'Origin \u6279\u5904\u7406\u5b8c\u6210\uff1a\u6210\u529f {success}/{total} \uff0c\u5931\u8d25 {failed}\u3002',
    da_settings_origin_batch_failed: 'Origin \u6279\u5904\u7406\u5931\u8d25\uff1a{error}',
    da_settings_origin_plot_title: '\u9ed8\u8ba4\u7ed8\u56fe\u8bbe\u7f6e',
    da_settings_origin_plot_desc: '\u9002\u7528\u4e8e\u201c\u5728 Origin \u4e2d\u6253\u5f00\u201d\u4ee5\u53ca batch/zip \u4efb\u52a1\u4e2d\u7684 Python \u56de\u9000\u7ed8\u56fe\u3002',
    da_settings_origin_plot_type_label: '\u7ed8\u56fe\u7c7b\u578b',
    da_settings_origin_plot_type_200: '200\uff08\u6563\u70b9\uff09',
    da_settings_origin_plot_type_201: '201\uff08\u6298\u7ebf\uff09',
    da_settings_origin_plot_type_202: '202\uff08\u6298\u7ebf+\u7b26\u53f7\uff09',
    da_settings_origin_plot_xy_pairs_label: 'XY \u914d\u5bf9',
    da_settings_origin_plot_xy_pairs_hint: 'LabTalk \u8868\u8fbe\u5f0f\uff0c\u4f8b\u5982 ((1,2)) \u6216 ((1,2),(3,4))\u3002',
    da_settings_origin_plot_command_label: '\u7ed8\u56fe\u547d\u4ee4\u8986\u76d6',
    da_settings_origin_plot_command_hint: '\u53ef\u9009\u5b8c\u6574 LabTalk \u547d\u4ee4\u3002\u8bbe\u7f6e\u540e\u5c06\u8986\u76d6\u7ed8\u56fe\u7c7b\u578b\u548c XY \u914d\u5bf9\u3002',
    da_settings_origin_plot_post_commands_label: '\u540e\u5904\u7406\u547d\u4ee4',
    da_settings_origin_plot_post_commands_hint: '\u6bcf\u884c\u4e00\u6761 LabTalk \u547d\u4ee4\uff0c\u7ed8\u56fe\u540e\u4f9d\u6b21\u6267\u884c\u3002',
    da_settings_origin_plot_saved: 'Origin \u7ed8\u56fe\u8bbe\u7f6e\u5df2\u66f4\u65b0\u3002',
    da_settings_origin_plot_save_failed: '\u66f4\u65b0\u7ed8\u56fe\u8bbe\u7f6e\u5931\u8d25\uff1a{error}',
    da_settings_origin_cleanup_title: '\u8fd0\u884c\u7f13\u5b58\u6e05\u7406',
    da_settings_origin_cleanup_desc: '\u63a7\u5236 .device/origin \u4e0b Origin \u8fd0\u884c\u4efb\u52a1\u7684\u81ea\u52a8\u6e05\u7406\u3002',
    da_settings_origin_cleanup_enable_label: '\u81ea\u52a8\u6e05\u7406',
    da_settings_origin_cleanup_enable_on: '\u5f00\u542f',
    da_settings_origin_cleanup_enable_off: '\u5173\u95ed',
    da_settings_origin_cleanup_keep_success_label: '\u4fdd\u7559\u6210\u529f\u4efb\u52a1\u6570',
    da_settings_origin_cleanup_failed_days_label: '\u4fdd\u7559\u5931\u8d25\u4efb\u52a1\u5929\u6570',
    da_settings_origin_cleanup_run_btn: '\u7acb\u5373\u6e05\u7406',
    da_settings_origin_cleanup_running: '\u6e05\u7406\u4e2d...',
    da_settings_origin_cleanup_saved: '\u5df2\u66f4\u65b0 Origin \u6e05\u7406\u8bbe\u7f6e\u3002',
    da_settings_origin_cleanup_save_failed: '\u66f4\u65b0\u6e05\u7406\u8bbe\u7f6e\u5931\u8d25\uff1a{error}',
    da_settings_origin_cleanup_run_success: '\u6e05\u7406\u5b8c\u6210\uff0c\u5df2\u79fb\u9664 {count} \u4e2a\u4efb\u52a1\u6587\u4ef6\u5939\u3002',
    da_settings_origin_cleanup_run_failed: '\u6e05\u7406\u5931\u8d25\uff1a{error}',
    da_stop_on_first_invalid_file: '首个无效即停止',
    da_overview_curve_filter_label: '\u66f2\u7ebf\u7b5b\u9009',
    da_overview_curve_filter_all: '\u5168\u90e8',
    da_overview_curve_filter_transfer: '\u8f6c\u79fb',
    da_overview_curve_filter_output: '\u8f93\u51fa',
    da_overview_sort_ymax_title: '\u6309 yMax \u6392\u5e8f\uff1a{order}',
    da_overview_sort_ymax_none: '\u4e0d\u6392\u5e8f',
    da_overview_sort_ymax_desc: '\u964d\u5e8f',
    da_overview_sort_ymax_asc: '\u5347\u5e8f',
    da_overview_processing: '\u5904\u7406\u4e2d {processed}/{total}',
    da_overview_select_mode_title: '\u753b\u5e03\u9009\u62e9\u6a21\u5f0f\uff1a{state}',
    da_overview_select_mode_on: '\u5f00\u542f',
    da_overview_select_mode_off: '\u5173\u95ed',
    da_overview_select_mode_toggle: '\u9009\u62e9',
    da_overview_select_badge: '\u5df2\u9009',
    da_overview_selected_num_figures: 'Selected {count} figures',
    da_tab_analysis: '分析与可视化',
    da_tab_data: '导入与提取',
    da_tab_switcher_label: '设备分析页面切换',
    da_template_discard_changes_desc: '你在“保存”面板有未保存的修改。要放弃这些修改并返回“选择”吗？',
    da_template_discard_changes_discard: '放弃修改',
    da_template_discard_changes_keep_editing: '继续编辑',
    da_template_discard_changes_title: '放弃修改？',
    da_template_mode: '模板模式',
    da_template_mode_save: '保存',
    da_template_mode_select: '选择',
    da_template_name: '模板名称',
    da_template_saved: '模板已保存',
    da_varPairBothOrNeither: 'Var1 和 Var2 必须同时留空或同时填写。',
    da_varPairCellOrText: 'Var1 和 Var2 只能同时使用单元格（如 A1）或同时使用文本（如 Vg），不允许混用。',
    da_yColumnsRequired: '请从预览表头中选择 Y 数据列。',
    unknownError: '未知错误',
  },
};

type LanguageProviderProps = {
  children: ReactNode;
};

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<LanguageCode>('zh');

  const t: TranslateFn = (key, vars: TranslationVars = {}) => {
    const template = translations[language]?.[key] ?? translations.en[key] ?? key;

    return Object.entries(vars).reduce((acc, [varKey, value]) => {
      return acc.replaceAll('{' + varKey + '}', String(value));
    }, template);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
