export const ipcChannels = {
  desktopMetaGet: "desktop:meta:get",
  desktopAutoUpdateStatusGet: "desktop:auto-update-status:get",
  desktopAutoUpdateStatusChanged: "desktop:auto-update-status:changed",
  desktopBootSettingsGet: "desktop-boot:settings:get",
  desktopBootUiReady: "desktop-boot:ui-ready",
  templatesGet: "device-analysis-store:templates:get",
  templatesCreate: "device-analysis-store:templates:create",
  templatesDelete: "device-analysis-store:templates:delete",
  settingsGet: "device-analysis-store:settings:get",
  settingsPatch: "device-analysis-store:settings:patch",
  persistencePathGet: "device-analysis-store:persistence-path:get",
  persistencePathSet: "device-analysis-store:persistence-path:set",
  persistencePathChoose: "device-analysis-store:persistence-path:choose",
  originExeGet: "device-analysis-origin:exe:get",
  originExeSet: "device-analysis-origin:exe:set",
  originExePick: "device-analysis-origin:exe:pick",
  originHealthCheck: "device-analysis-origin:health-check",
  originRunCsv: "device-analysis-origin:run-csv",
  originRuntimeCleanupRun: "device-analysis-origin:runtime-cleanup:run",
  excelConvertRust: "device-analysis-excel:convert-rust",
  excelReadConvertedCsv: "device-analysis-excel:read-converted-csv",
  analysisDemoFilesGet: "device-analysis-demo:files:get",
  analysisRustEngineOpen: "device-analysis-rust-engine:open",
  analysisRustEnginePreviewMeta: "device-analysis-rust-engine:preview-meta",
  analysisRustEnginePreviewRows: "device-analysis-rust-engine:preview-rows",
  analysisRustEngineReadCell: "device-analysis-rust-engine:read-cell",
  analysisRustEngineReadCells: "device-analysis-rust-engine:read-cells",
  analysisRustEngineInferAutoExtraction:
    "device-analysis-rust-engine:infer-auto-extraction",
  analysisRustEngineProcessFile: "device-analysis-rust-engine:process-file",
  analysisRustEngineAnalyzeRc: "device-analysis-rust-engine:analyze-rc",
  analysisRustEngineExportOriginCsv:
    "device-analysis-rust-engine:export-origin-csv",
  analysisOriginZipSave: "device-analysis-origin:zip:save",
  analysisRustEngineDispose: "device-analysis-rust-engine:dispose",
} as const;
